import { expect, test } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const APP_ORIGIN = process.env.UI_AUDIT_BASE_URL || 'http://localhost:3001';

test.describe('uni folia frontend audit smoke', () => {
  test('mobile dashboard keeps the navigation collapsed by default', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(`${APP_ORIGIN}/`, { waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(1500);

    await expect(page.getByTestId('layout-sidebar')).toHaveClass(/-translate-x-full/);
    await expect(page.getByTestId('layout-sidebar-toggle')).toBeVisible();
    await expect(page.locator('main')).toContainText('Uni Folia');
  });

  test('record page removes critical unlabeled-control issues', async ({ page }) => {
    await page.goto(`${APP_ORIGIN}/app/record`, { waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(2000);

    const axe = await new AxeBuilder({ page }).analyze();
    const criticalIds = axe.violations
      .filter((violation) => violation.impact === 'critical')
      .map((violation) => violation.id);

    expect(criticalIds).not.toContain('button-name');
    expect(criticalIds).not.toContain('label');
  });

  test('workshop apply flow keeps an explicit AI marker before save', async ({ page }) => {
    await page.route('**/api/v1/drafts/chat/stream', async (route) => {
      const body = [
        'data: {"token":"Mock assistant reply.\\n\\n[CONTENT]Student-authored evidence paragraph draft: I recorded sensor drift across three club test runs and compared the method limits in my notes.[/CONTENT]"}',
        '',
        'data: {"status":"DONE"}',
        '',
      ].join('\n');

      await route.fulfill({
        status: 200,
        contentType: 'text/event-stream',
        body,
      });
    });

    await page.goto(`${APP_ORIGIN}/app/workshop`, { waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(2000);

    const input = page.locator('input').last();
    await input.fill('Give me one evidence-backed paragraph draft.');
    await input.press('Enter');
    await page.waitForTimeout(2000);

    const applyButton = page.getByRole('button', { name: '이 내용을 보고서에 추가' }).first();
    await expect(applyButton).toBeVisible();
    await applyButton.click();
    await page.waitForTimeout(800);

    // Accept via modal
    const confirmButton = page.getByRole('button', { name: '문서 끝에 안전하게 추가' });
    await expect(confirmButton).toBeVisible();
    await confirmButton.click();
    await page.waitForTimeout(800);

    await expect(page.getByTestId('workshop-draft-preview')).toContainText('[AI Draft Suggestion]');
    await expect(page.getByTestId('workshop-draft-preview')).toContainText(
      'This text was generated by Foli and is not student-authored',
    );

    await page.getByTestId('workshop-save-draft').click();
    await page.waitForTimeout(800);

    const archiveRaw = await page.evaluate(() => localStorage.getItem('polio_archive_items'));
    expect(archiveRaw).toBeTruthy();
    expect(archiveRaw).toContain('Student-authored evidence paragraph draft');
  });

  test('workshop chat falls back to helpful Korean task guidance on failure', async ({ page }) => {
    await page.route('**/api/v1/drafts/chat/stream', async (route) => {
      await route.abort('failed');
    });

    await page.goto(`${APP_ORIGIN}/app/workshop`, { waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(2000);

    const input = page.locator('input').last();
    await input.fill('연구 주제 좁히는 것 좀 도와줘.'); // Korean task input
    await input.press('Enter');
    await page.waitForTimeout(1000);

    // Should NOT contain "Demo fallback" or English robotic text
    await expect(page.locator('main')).not.toContainText('Demo fallback');
    await expect(page.locator('main')).toContainText('주제를 구체적인 질문으로 좁히기');
  });

  test('workshop chat handles casual Korean greetings gracefully on failure', async ({ page }) => {
    await page.route('**/api/v1/drafts/chat/stream', async (route) => {
      await route.abort('failed');
    });

    await page.goto(`${APP_ORIGIN}/app/workshop`, { waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(1000);

    const input = page.locator('input').last();
    await input.fill('안녕'); // Casual greeting
    await input.press('Enter');
    await page.waitForTimeout(1000);

    await expect(page.locator('main')).toContainText('안녕하세요! Uni Folia 방문을 환영해요');
    await expect(page.locator('main')).not.toContainText('연결이 원활하지 않아'); // Don't mention errors on greetings if possible
  });

  test('workshop chat handles casual English greetings gracefully on failure', async ({ page }) => {
    await page.route('**/api/v1/drafts/chat/stream', async (route) => {
      await route.abort('failed');
    });

    await page.goto(`${APP_ORIGIN}/app/workshop`, { waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(1000);

    const input = page.locator('input').last();
    await input.fill('Hello!'); // English greeting
    await input.press('Enter');
    await page.waitForTimeout(1000);

    await expect(page.locator('main')).toContainText('Hello! Welcome to Uni Folia');
    await expect(page.locator('main')).not.toContainText('currently limited'); // Keep greetings clean
  });

  test('workshop chat falls back to helpful English task guidance on failure', async ({ page }) => {
    await page.route('**/api/v1/drafts/chat/stream', async (route) => {
      await route.abort('failed');
    });

    await page.goto(`${APP_ORIGIN}/app/workshop`, { waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(1000);

    const input = page.locator('input').last();
    await input.fill('Help me with evidence.'); // English task
    await input.press('Enter');
    await page.waitForTimeout(1000);

    await expect(page.locator('main')).toContainText('unable to verify evidence');
    await expect(page.locator('main')).toContainText('Outlining the overall structure');
  });

  test('diagnosis flow shows retryable job failure and evidence-backed result', async ({ page }) => {
    let retried = false;
    let completedPolls = 0;

    await page.route('**/api/v1/diagnosis/**', async (route) => {
      const url = route.request().url();
      if (url.endsWith('/api/v1/diagnosis/run')) {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            id: 'run-1',
            project_id: 'project-1',
            status: 'PENDING',
            result_payload: null,
            error_message: null,
            review_required: false,
            policy_flags: [],
            citations: [],
            response_trace_id: null,
            async_job_id: 'job-1',
            async_job_status: 'queued',
          }),
        });
        return;
      }

      if (url.endsWith('/api/v1/diagnosis/run-1')) {
        if (!retried) {
          await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
              id: 'run-1',
              project_id: 'project-1',
              status: 'FAILED',
              result_payload: null,
              error_message: 'Temporary model timeout.',
              review_required: false,
              policy_flags: [],
              citations: [],
              response_trace_id: null,
              async_job_id: 'job-1',
              async_job_status: 'failed',
            }),
          });
          return;
        }

        completedPolls += 1;
        if (completedPolls === 1) {
          await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify({
              id: 'run-1',
              project_id: 'project-1',
              status: 'RUNNING',
              result_payload: null,
              error_message: null,
              review_required: false,
              policy_flags: [],
              citations: [],
              response_trace_id: null,
              async_job_id: 'job-1',
              async_job_status: 'running',
            }),
          });
          return;
        }

        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            id: 'run-1',
            project_id: 'project-1',
            status: 'COMPLETED',
            result_payload: {
              headline: 'The record is grounded enough to continue with a narrower CS inquiry.',
              strengths: ['The upload shows a real measurement and comparison trail.'],
              gaps: ['Method limits are still thin in the current record.'],
              risk_level: 'warning',
              recommended_focus: 'Add one explicit method limit and one reflection before drafting.',
              citations: [
                {
                  source_label: 'student-record.pdf',
                  page_number: 2,
                  excerpt: 'I compared three sensor logs and documented the drift pattern.',
                  relevance_score: 1.2,
                },
              ],
              review_required: true,
              response_trace_id: 'trace-1',
            },
            error_message: null,
            review_required: true,
            policy_flags: [
              {
                id: 'flag-1',
                code: 'sensitive_student_id',
                severity: 'medium',
                detail: 'Input text contains a student identifier.',
                matched_text: '20240001',
                match_count: 1,
                status: 'open',
                created_at: '2026-03-29T00:00:00Z',
              },
            ],
            citations: [
              {
                source_label: 'student-record.pdf',
                page_number: 2,
                excerpt: 'I compared three sensor logs and documented the drift pattern.',
                relevance_score: 1.2,
              },
            ],
            response_trace_id: 'trace-1',
            async_job_id: 'job-1',
            async_job_status: 'succeeded',
          }),
        });
      }
    });

    await page.route('**/api/v1/jobs/**', async (route) => {
      const url = route.request().url();
      if (url.endsWith('/retry')) {
        retried = true;
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            id: 'job-1',
            project_id: 'project-1',
            job_type: 'diagnosis',
            resource_type: 'diagnosis_run',
            resource_id: 'run-1',
            status: 'queued',
            retry_count: 2,
            max_retries: 2,
            failure_reason: null,
            failure_history: [],
            next_attempt_at: '2026-03-29T00:00:00Z',
            started_at: null,
            completed_at: null,
            dead_lettered_at: null,
            created_at: '2026-03-29T00:00:00Z',
            updated_at: '2026-03-29T00:00:00Z',
          }),
        });
        return;
      }

      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          id: 'job-1',
          project_id: 'project-1',
          job_type: 'diagnosis',
          resource_type: 'diagnosis_run',
          resource_id: 'run-1',
          status: retried ? 'running' : 'failed',
          retry_count: 2,
          max_retries: 2,
          failure_reason: retried ? null : 'Temporary model timeout.',
          failure_history: [],
          next_attempt_at: '2026-03-29T00:00:00Z',
          started_at: '2026-03-29T00:00:00Z',
          completed_at: retried ? null : '2026-03-29T00:00:05Z',
          dead_lettered_at: retried ? null : '2026-03-29T00:00:05Z',
          created_at: '2026-03-29T00:00:00Z',
          updated_at: '2026-03-29T00:00:05Z',
        }),
      });
    });

    await page.route('**/api/v1/documents/upload', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ project_id: 'project-1', id: 'doc-1' }),
      });
    });

    await page.route('**/api/v1/documents/doc-1/parse', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ status: 'parsed' }),
      });
    });

    await page.goto(`${APP_ORIGIN}/app/diagnosis`, { waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(1000);

    await page.getByTestId('diagnosis-edit-goals').click();
    await page.getByTestId('diagnosis-university-search').fill('서울대학교');
    await page.getByTestId('diagnosis-university-option-0').click();
    await page.getByTestId('diagnosis-major-search').fill('컴퓨터공학');
    await page.getByTestId('diagnosis-major-option-0').click();
    await page.getByTestId('diagnosis-add-goal').click();
    await page.getByTestId('diagnosis-save-goals').click();
    await page.getByTestId('diagnosis-goals-continue').click();

    await page.getByTestId('diagnosis-upload-input').setInputFiles({
      name: 'student-record.pdf',
      mimeType: 'application/pdf',
      buffer: Buffer.from('%PDF-1.4 mock pdf'),
    });

    await expect(page.getByTestId('diagnosis-job-status')).toContainText('Temporary model timeout.');
    await page.getByTestId('diagnosis-job-retry').click();

    await expect(page.getByTestId('diagnosis-result-panel')).toBeVisible();
    await expect(page.getByTestId('diagnosis-evidence-panel')).toContainText('student-record.pdf');
    await expect(page.getByTestId('diagnosis-review-panel')).toContainText('Manual review recommended');
  });
});
