# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import Iterable, Literal, TypedDict


SuggestionType = Literal["interest", "subject", "major"]


class TopicExample(TypedDict, total=False):
    id: str
    label: str
    suggestion_type: SuggestionType
    reason: str
    subject: str
    major: str
    keywords: list[str]


_DOMAIN_SEEDS: tuple[dict[str, str], ...] = (
    {
        "id": "math-stat",
        "subject": "수학/확률과 통계",
        "major": "데이터사이언스",
        "anchor": "학교 급식 만족도와 잔반량",
        "core_concept": "상관관계와 회귀",
        "social_issue": "식품 낭비 감소",
        "tool": "수요 예측표",
        "everyday_object": "급식 메뉴 선택",
        "metric": "잔반량",
        "ethical_conflict": "개인 선호와 영양 균형의 충돌",
        "stakeholder": "학생과 영양교사",
        "data_source": "급식 선호 설문과 잔반 관찰 기록",
        "local_site": "학교 식당",
        "student_action": "표본 설계와 회귀식 비교",
        "risk": "표본 편향",
        "output": "메뉴 추천 기준",
        "theory": "최소제곱법",
        "method": "회귀분석",
    },
    {
        "id": "physics-energy",
        "subject": "물리학",
        "major": "신재생에너지공학",
        "anchor": "교실 조도와 태양광 발전량",
        "core_concept": "에너지 전환 효율",
        "social_issue": "학교 전력 절감",
        "tool": "미니 태양광 충전 시스템",
        "everyday_object": "창가 조도 변화",
        "metric": "발전 전압과 충전 시간",
        "ethical_conflict": "비용 절감과 안전성의 충돌",
        "stakeholder": "학생과 시설 담당자",
        "data_source": "조도 센서와 전압 측정값",
        "local_site": "교실 창가",
        "student_action": "각도별 발전량 측정",
        "risk": "날씨 변수",
        "output": "교실형 에너지 절감 제안서",
        "theory": "광전 효과와 전력 공식",
        "method": "센서 측정",
    },
    {
        "id": "chem-material",
        "subject": "화학",
        "major": "재료공학",
        "anchor": "천연 고분자 필름의 강도 변화",
        "core_concept": "분자 간 결합과 가교",
        "social_issue": "일회용 플라스틱 대체",
        "tool": "생분해성 포장 필름",
        "everyday_object": "전분 필름",
        "metric": "인장 강도와 분해 속도",
        "ethical_conflict": "친환경성과 내구성의 충돌",
        "stakeholder": "소비자와 제조업체",
        "data_source": "농도별 필름 실험 기록",
        "local_site": "과학실",
        "student_action": "가소제 비율별 시편 제작",
        "risk": "반복 실험 부족",
        "output": "친환경 소재 비교표",
        "theory": "고분자 네트워크",
        "method": "조건 통제 실험",
    },
    {
        "id": "bio-microbiome",
        "subject": "생명과학",
        "major": "의생명과학",
        "anchor": "발효식품과 미생물 다양성",
        "core_concept": "미생물 군집과 항상성",
        "social_issue": "청소년 식습관 개선",
        "tool": "발효 조건 비교 실험",
        "everyday_object": "요거트와 김치",
        "metric": "pH 변화와 발효 속도",
        "ethical_conflict": "개인 건강 데이터 활용의 한계",
        "stakeholder": "학생과 보건교사",
        "data_source": "발효 시간별 pH 측정값",
        "local_site": "가정과 과학실",
        "student_action": "온도 조건별 발효 관찰",
        "risk": "오염 변수",
        "output": "건강 식습관 탐구 보고서",
        "theory": "효소 활성과 미생물 대사",
        "method": "비교 관찰",
    },
    {
        "id": "earth-climate",
        "subject": "지구과학",
        "major": "기후환경학",
        "anchor": "학교 주변 열섬 현상",
        "core_concept": "복사 평형과 열용량",
        "social_issue": "폭염 취약 공간 개선",
        "tool": "그늘 지도와 온도 완화 설계",
        "everyday_object": "운동장과 보도블록",
        "metric": "표면 온도 차이",
        "ethical_conflict": "개발 편의와 기후 적응의 충돌",
        "stakeholder": "학생과 지역 주민",
        "data_source": "시간대별 표면 온도 측정값",
        "local_site": "학교 운동장",
        "student_action": "재질별 온도 지도 작성",
        "risk": "측정 시간 편향",
        "output": "학교 열섬 완화 제안",
        "theory": "알베도와 열수지",
        "method": "현장 관측",
    },
    {
        "id": "env-circular",
        "subject": "환경과학",
        "major": "환경공학",
        "anchor": "교내 분리배출 실패 패턴",
        "core_concept": "물질 순환과 행동 유도",
        "social_issue": "재활용 오염률 감소",
        "tool": "분리배출 안내 디자인",
        "everyday_object": "교실 쓰레기통",
        "metric": "오분류 비율",
        "ethical_conflict": "편의성과 환경 책임의 충돌",
        "stakeholder": "학생과 청소 노동자",
        "data_source": "분리배출 실태 관찰표",
        "local_site": "교내 복도",
        "student_action": "안내문 A/B 테스트",
        "risk": "관찰자 효과",
        "output": "순환경제 실천 가이드",
        "theory": "넛지 이론",
        "method": "행동 실험",
    },
    {
        "id": "cs-ai",
        "subject": "정보",
        "major": "인공지능학",
        "anchor": "학교 공지 분류 자동화",
        "core_concept": "텍스트 분류와 벡터화",
        "social_issue": "정보 접근성 개선",
        "tool": "공지 요약 챗봇",
        "everyday_object": "학교 알림장",
        "metric": "분류 정확도",
        "ethical_conflict": "자동화 편의와 정보 누락 위험",
        "stakeholder": "학생과 담임교사",
        "data_source": "공지 제목과 카테고리 목록",
        "local_site": "학급 온라인 게시판",
        "student_action": "규칙 기반 분류기와 AI 분류기 비교",
        "risk": "학습 데이터 편향",
        "output": "학교 공지 분류 프로토타입",
        "theory": "TF-IDF와 임베딩",
        "method": "알고리즘 비교",
    },
    {
        "id": "data-justice",
        "subject": "사회문제탐구",
        "major": "데이터정책학",
        "anchor": "공공데이터로 본 지역 서비스 격차",
        "core_concept": "지표 설계와 표준화",
        "social_issue": "지역 불평등 완화",
        "tool": "격차 지수 대시보드",
        "everyday_object": "공공시설 접근성",
        "metric": "도보 접근 시간",
        "ethical_conflict": "효율성과 형평성의 충돌",
        "stakeholder": "청소년과 지방자치단체",
        "data_source": "공공시설 위치와 인구 통계",
        "local_site": "거주 지역 생활권",
        "student_action": "지도 기반 접근성 비교",
        "risk": "자료 최신성",
        "output": "지역 격차 분석 카드뉴스",
        "theory": "표준화 점수",
        "method": "공공데이터 분석",
    },
    {
        "id": "medicine-digital",
        "subject": "보건",
        "major": "의학",
        "anchor": "웨어러블 수면 기록과 학습 집중도",
        "core_concept": "생체 리듬과 항상성",
        "social_issue": "청소년 수면 부족",
        "tool": "수면 위생 개선 체크리스트",
        "everyday_object": "스마트워치 수면 기록",
        "metric": "수면 시간과 주관적 집중도",
        "ethical_conflict": "건강관리와 개인정보 보호의 충돌",
        "stakeholder": "학생과 보호자",
        "data_source": "자가 기록 수면 일지",
        "local_site": "학급",
        "student_action": "수면 습관 전후 비교",
        "risk": "자가보고 오류",
        "output": "청소년 건강 개선 보고서",
        "theory": "일주기 리듬",
        "method": "자가 추적 분석",
    },
    {
        "id": "nursing-care",
        "subject": "보건/윤리",
        "major": "간호학",
        "anchor": "학교 응급상황 대응 절차",
        "core_concept": "중증도 분류와 의사소통",
        "social_issue": "안전한 학교 보건 체계",
        "tool": "응급 대응 플로차트",
        "everyday_object": "보건실 방문 사례",
        "metric": "대응 시간과 정보 전달 정확도",
        "ethical_conflict": "신속 대응과 학생 프라이버시의 충돌",
        "stakeholder": "학생과 보건교사",
        "data_source": "가상 사례별 대응 시나리오",
        "local_site": "보건실",
        "student_action": "상황별 의사소통 문구 설계",
        "risk": "전문 의료 판단 과장",
        "output": "응급 소통 매뉴얼",
        "theory": "환자 안전 문화",
        "method": "시나리오 분석",
    },
    {
        "id": "psych-attention",
        "subject": "심리학",
        "major": "인지과학",
        "anchor": "스마트폰 알림과 집중 지속 시간",
        "core_concept": "주의 전환과 작업기억",
        "social_issue": "학습 몰입 저하",
        "tool": "집중 방해 요인 체크 앱",
        "everyday_object": "스마트폰 알림",
        "metric": "과제 수행 시간",
        "ethical_conflict": "디지털 연결성과 자기통제의 충돌",
        "stakeholder": "학생과 교사",
        "data_source": "알림 조건별 수행 기록",
        "local_site": "자습실",
        "student_action": "알림 차단 조건 비교",
        "risk": "개인차 변수",
        "output": "학습 몰입 전략 제안서",
        "theory": "인지 부하 이론",
        "method": "소규모 행동 실험",
    },
    {
        "id": "education-feedback",
        "subject": "교육학",
        "major": "교육공학",
        "anchor": "피드백 방식과 문제 재도전율",
        "core_concept": "형성평가와 메타인지",
        "social_issue": "학습 격차 완화",
        "tool": "개별 피드백 카드",
        "everyday_object": "오답노트",
        "metric": "재풀이 성공률",
        "ethical_conflict": "개인화와 낙인 효과의 충돌",
        "stakeholder": "학생과 교사",
        "data_source": "오답 피드백 전후 기록",
        "local_site": "교실",
        "student_action": "피드백 문구 유형 비교",
        "risk": "동기 수준 차이",
        "output": "학습 피드백 설계안",
        "theory": "성장 마인드셋",
        "method": "수업 개선 실험",
    },
    {
        "id": "econ-household",
        "subject": "경제",
        "major": "경제학",
        "anchor": "편의점 가격 변화와 소비 선택",
        "core_concept": "수요 탄력성",
        "social_issue": "생활 물가 부담",
        "tool": "가격 민감도 분석표",
        "everyday_object": "간식 구매",
        "metric": "가격 대비 구매 의향",
        "ethical_conflict": "기업 이윤과 소비자 후생의 충돌",
        "stakeholder": "소비자와 판매자",
        "data_source": "가격 조사와 구매 의향 설문",
        "local_site": "학교 주변 상권",
        "student_action": "대체재 가격 비교",
        "risk": "표본 규모 부족",
        "output": "생활경제 분석 보고서",
        "theory": "가격 탄력성",
        "method": "시장 조사",
    },
    {
        "id": "business-esg",
        "subject": "경영",
        "major": "경영학",
        "anchor": "학교 매점 ESG 소비 선택",
        "core_concept": "브랜드 신뢰와 소비자 가치",
        "social_issue": "윤리적 소비 확산",
        "tool": "ESG 제품 평가 루브릭",
        "everyday_object": "매점 간식",
        "metric": "구매 의향과 가격 프리미엄",
        "ethical_conflict": "저렴한 가격과 지속가능성의 충돌",
        "stakeholder": "학생 소비자와 판매자",
        "data_source": "제품 표시 정보와 설문",
        "local_site": "학교 매점",
        "student_action": "제품별 가치 제안 비교",
        "risk": "브랜드 정보 왜곡",
        "output": "윤리적 소비 캠페인 기획서",
        "theory": "고객 가치 제안",
        "method": "소비자 조사",
    },
    {
        "id": "sociology-inclusion",
        "subject": "사회문화",
        "major": "사회학",
        "anchor": "학교 공간 이용의 배제 경험",
        "core_concept": "사회적 배제와 규범",
        "social_issue": "포용적 학교 문화",
        "tool": "공간 접근성 개선안",
        "everyday_object": "동아리실과 휴게 공간",
        "metric": "이용 빈도와 소속감",
        "ethical_conflict": "다수 편의와 소수 접근권의 충돌",
        "stakeholder": "학생 집단과 학교",
        "data_source": "공간 이용 설문과 관찰 기록",
        "local_site": "교내 공용 공간",
        "student_action": "공간 이용 패턴 비교",
        "risk": "민감 정보 노출",
        "output": "포용 공간 개선 제안",
        "theory": "사회적 자본",
        "method": "질적 인터뷰",
    },
    {
        "id": "law-rights",
        "subject": "정치와 법",
        "major": "법학",
        "anchor": "학교 생활 규정과 학생 권리",
        "core_concept": "기본권 제한과 비례성",
        "social_issue": "학생 인권과 공동체 질서",
        "tool": "규정 검토 체크리스트",
        "everyday_object": "휴대전화 사용 규정",
        "metric": "침해 최소성과 목적 적합성",
        "ethical_conflict": "질서 유지와 자기결정권의 충돌",
        "stakeholder": "학생과 학교",
        "data_source": "생활 규정 조항과 사례",
        "local_site": "학생 자치회",
        "student_action": "규정별 비례성 검토",
        "risk": "법률 해석 과장",
        "output": "학생 자치 정책 제안서",
        "theory": "비례의 원칙",
        "method": "사례 비교",
    },
    {
        "id": "media-algorithm",
        "subject": "미디어",
        "major": "커뮤니케이션학",
        "anchor": "숏폼 추천 알고리즘과 정보 편식",
        "core_concept": "필터버블과 프레이밍",
        "social_issue": "미디어 리터러시 향상",
        "tool": "추천 피드 점검표",
        "everyday_object": "숏폼 영상 피드",
        "metric": "주제 다양성 지수",
        "ethical_conflict": "개인화와 공론장 다양성의 충돌",
        "stakeholder": "청소년 이용자와 플랫폼",
        "data_source": "추천 영상 카테고리 기록",
        "local_site": "개인 미디어 사용 환경",
        "student_action": "계정 조건별 추천 피드 비교",
        "risk": "플랫폼 정책 변화",
        "output": "미디어 리터러시 가이드",
        "theory": "의제 설정 이론",
        "method": "콘텐츠 분석",
    },
    {
        "id": "literature-ai",
        "subject": "국어/문학",
        "major": "인문콘텐츠학",
        "anchor": "AI 생성 문장과 인간 서사의 차이",
        "core_concept": "화자와 서술 관점",
        "social_issue": "창작 윤리와 저작권",
        "tool": "서사성 평가 기준표",
        "everyday_object": "웹소설 도입부",
        "metric": "몰입도와 개연성",
        "ethical_conflict": "창작 보조와 표절의 충돌",
        "stakeholder": "창작자와 독자",
        "data_source": "인간 작성문과 AI 생성문 비교",
        "local_site": "독서 토론 모임",
        "student_action": "문체 요소별 비교 분석",
        "risk": "취향 평가의 주관성",
        "output": "AI 시대 문학 비평문",
        "theory": "서사학",
        "method": "텍스트 비교",
    },
    {
        "id": "history-memory",
        "subject": "역사",
        "major": "역사교육",
        "anchor": "지역 기념물과 기억의 정치",
        "core_concept": "사료 비판과 역사 해석",
        "social_issue": "지역 정체성 형성",
        "tool": "기념물 해설 카드",
        "everyday_object": "지역 표지석",
        "metric": "해설의 관점 다양성",
        "ethical_conflict": "기념과 비판적 기억의 충돌",
        "stakeholder": "지역 주민과 학생",
        "data_source": "기념물 안내문과 신문 자료",
        "local_site": "지역 역사 유적",
        "student_action": "사료 출처별 관점 비교",
        "risk": "현재 관점의 과잉 투사",
        "output": "지역사 탐방 해설문",
        "theory": "역사적 맥락화",
        "method": "사료 분석",
    },
    {
        "id": "architecture-comfort",
        "subject": "기술가정/물리",
        "major": "건축학",
        "anchor": "교실 창 배치와 열쾌적성",
        "core_concept": "채광과 환기",
        "social_issue": "학습 공간 질 개선",
        "tool": "교실 리모델링 평면안",
        "everyday_object": "창문과 블라인드",
        "metric": "온도와 눈부심 정도",
        "ethical_conflict": "비용과 사용자 편의의 충돌",
        "stakeholder": "학생과 학교 시설팀",
        "data_source": "온습도와 조도 측정값",
        "local_site": "교실",
        "student_action": "좌석 위치별 환경 측정",
        "risk": "계절 변수",
        "output": "학습 공간 개선 도면",
        "theory": "패시브 디자인",
        "method": "환경 측정",
    },
    {
        "id": "urban-mobility",
        "subject": "지리/사회",
        "major": "도시공학",
        "anchor": "등하굣길 보행 안전",
        "core_concept": "접근성과 위험 노출",
        "social_issue": "청소년 교통 안전",
        "tool": "위험 구간 개선 지도",
        "everyday_object": "횡단보도와 버스정류장",
        "metric": "보행 시간과 위험 지점 수",
        "ethical_conflict": "차량 흐름과 보행권의 충돌",
        "stakeholder": "학생과 운전자",
        "data_source": "등하굣길 관찰 기록",
        "local_site": "학교 주변 도로",
        "student_action": "동선별 위험도 매핑",
        "risk": "관찰 시간 편향",
        "output": "안전 통학로 제안서",
        "theory": "보행 친화 도시",
        "method": "지도화 분석",
    },
    {
        "id": "design-accessibility",
        "subject": "미술/정보",
        "major": "UX디자인",
        "anchor": "학교 안내문의 가독성",
        "core_concept": "시각 위계와 접근성",
        "social_issue": "정보 소외 감소",
        "tool": "접근성 개선 포스터",
        "everyday_object": "교내 안내문",
        "metric": "정보 찾는 시간",
        "ethical_conflict": "미적 표현과 접근성의 충돌",
        "stakeholder": "학생과 방문자",
        "data_source": "안내문 이해도 테스트",
        "local_site": "교내 게시판",
        "student_action": "디자인 전후 사용성 비교",
        "risk": "테스트 표본 편향",
        "output": "유니버설 디자인 제안",
        "theory": "게슈탈트 원리",
        "method": "사용성 테스트",
    },
    {
        "id": "sports-biomech",
        "subject": "체육/물리",
        "major": "스포츠과학",
        "anchor": "농구 슛 각도와 성공률",
        "core_concept": "포물선 운동",
        "social_issue": "부상 예방과 운동 효율",
        "tool": "동작 분석 피드백표",
        "everyday_object": "스마트폰 슬로모션 영상",
        "metric": "발사각과 성공률",
        "ethical_conflict": "성과 향상과 부상 위험의 충돌",
        "stakeholder": "선수와 코치",
        "data_source": "동작 영상과 성공 횟수",
        "local_site": "체육관",
        "student_action": "각도별 슛 궤적 비교",
        "risk": "피로도 변수",
        "output": "운동 기술 개선 보고서",
        "theory": "운동역학",
        "method": "영상 분석",
    },
    {
        "id": "food-agri",
        "subject": "생명과학/화학",
        "major": "식품공학",
        "anchor": "저당 음료의 단맛 인식",
        "core_concept": "감각 수용과 농도",
        "social_issue": "청소년 당 섭취 감소",
        "tool": "저당 레시피 개선안",
        "everyday_object": "학교 음료",
        "metric": "당도와 선호도",
        "ethical_conflict": "맛 선호와 건강의 충돌",
        "stakeholder": "학생과 식품 제조사",
        "data_source": "당도 측정과 블라인드 선호 조사",
        "local_site": "가정과 실습실",
        "student_action": "농도별 선호도 비교",
        "risk": "개인 취향 편차",
        "output": "건강 음료 제안서",
        "theory": "감각 역치",
        "method": "블라인드 테스트",
    },
    {
        "id": "music-acoustics",
        "subject": "음악/물리",
        "major": "음향공학",
        "anchor": "교실 소음과 말소리 명료도",
        "core_concept": "파동과 공명",
        "social_issue": "수업 집중 환경 개선",
        "tool": "소음 저감 배치안",
        "everyday_object": "책상 배치와 벽면 재질",
        "metric": "데시벨과 명료도",
        "ethical_conflict": "공간 활용과 음향 품질의 충돌",
        "stakeholder": "학생과 교사",
        "data_source": "위치별 소음 측정값",
        "local_site": "교실",
        "student_action": "흡음 재료별 소음 비교",
        "risk": "측정기 오차",
        "output": "교실 음향 개선 제안",
        "theory": "음파 반사와 흡수",
        "method": "음향 측정",
    },
    {
        "id": "robotics-assistive",
        "subject": "공학/정보",
        "major": "로봇공학",
        "anchor": "교내 물품 운반 보조 로봇",
        "core_concept": "센서 제어와 경로 탐색",
        "social_issue": "이동 약자 지원",
        "tool": "라인트레이싱 운반 로봇",
        "everyday_object": "교내 이동 동선",
        "metric": "주행 성공률과 회전 오차",
        "ethical_conflict": "자동화 편의와 안전 책임의 충돌",
        "stakeholder": "학생과 교직원",
        "data_source": "경로별 주행 실험 기록",
        "local_site": "학교 복도",
        "student_action": "센서 위치별 오류 비교",
        "risk": "장애물 변수",
        "output": "보조 로봇 프로토타입 보고서",
        "theory": "피드백 제어",
        "method": "프로토타이핑",
    },
)


_ANGLE_TEMPLATES: tuple[dict[str, str], ...] = (
    {
        "id": "variable-sensitivity",
        "type": "subject",
        "title": "{anchor} 데이터를 활용한 {core_concept} 변수 민감도 분석",
        "reason": "{subject}의 핵심 개념을 실제 데이터로 검증하고, 변수 하나가 결과를 얼마나 바꾸는지 고교 수준에서 설명할 수 있습니다.",
    },
    {
        "id": "local-prediction",
        "type": "subject",
        "title": "{local_site}에서 관찰한 {data_source}를 활용한 {metric} 예측 모델 설계",
        "reason": "학교 안에서 직접 수집 가능한 근거를 쓰기 때문에 수행 진실성이 높고, 예측과 한계를 함께 보여줄 수 있습니다.",
    },
    {
        "id": "everyday-impact",
        "type": "interest",
        "title": "{everyday_object} 사용 패턴이 {social_issue}에 미치는 영향 실험",
        "reason": "일상 경험을 출발점으로 삼아 학생의 문제의식, 관찰력, 실천적 개선 과정을 자연스럽게 드러냅니다.",
    },
    {
        "id": "major-tool-audit",
        "type": "major",
        "title": "{major} 관점에서 {tool}의 효과와 한계 비교",
        "reason": "목표 전공과 연결되면서도 단순 찬양이 아니라 성능, 비용, 윤리의 균형을 평가하는 주제입니다.",
    },
    {
        "id": "error-analysis",
        "type": "subject",
        "title": "{theory} 개념을 적용한 {student_action} 설계 및 오차 요인 분석",
        "reason": "결과보다 과정과 오차 해석을 강조해 입학사정관이 보는 탐구 설계 역량을 보여주기 좋습니다.",
    },
    {
        "id": "ethics-tradeoff",
        "type": "major",
        "title": "{ethical_conflict} 상황에서 {stakeholder} 의사결정 기준 만들기",
        "reason": "전공 지식의 사회적 책임을 다루며, 찬반을 넘어 판단 기준을 설계하는 깊이 있는 주제입니다.",
    },
    {
        "id": "risk-reduction",
        "type": "subject",
        "title": "{risk}를 줄이기 위한 {method} 기반 탐구 프로토콜 설계",
        "reason": "탐구의 약점을 스스로 통제하려는 태도가 드러나며, 보고서의 신뢰도를 높이는 구조로 확장됩니다.",
    },
    {
        "id": "improvement-proposal",
        "type": "interest",
        "title": "{anchor} 사례를 바탕으로 {output} 개선안 제안",
        "reason": "관찰에서 끝나지 않고 개선안까지 이어져 세특에 기록하기 좋은 문제 해결 흐름을 만듭니다.",
    },
    {
        "id": "indicator-design",
        "type": "major",
        "title": "{data_source} 자료를 바탕으로 {major} 진로 역량을 보여주는 지표 설계",
        "reason": "전공 적합성을 막연한 관심이 아니라 측정 가능한 지표와 근거로 설명할 수 있습니다.",
    },
    {
        "id": "mini-experiment",
        "type": "subject",
        "title": "{core_concept} 개념을 검증하는 미니 실험: {everyday_object}를 중심으로",
        "reason": "거창한 장비 없이도 개념 이해와 실험 통제 능력을 보여주는 현실적인 심화 탐구입니다.",
    },
    {
        "id": "school-action",
        "type": "interest",
        "title": "{social_issue} 해결을 위한 학교 안 행동 실험과 피드백 분석",
        "reason": "학생이 실제로 바꿀 수 있는 범위에서 실천, 피드백, 재설계를 모두 담을 수 있습니다.",
    },
    {
        "id": "before-after",
        "type": "major",
        "title": "{tool} 도입 전후 {metric} 변화를 비교하는 준실험 설계",
        "reason": "전공 도구의 효과를 막연히 주장하지 않고 전후 비교로 검증해 설득력을 확보합니다.",
    },
    {
        "id": "counterexample",
        "type": "subject",
        "title": "{theory}와 {core_concept}을 연결한 반례 및 적용 한계 탐구",
        "reason": "잘 되는 사례보다 한계를 찾는 방식이라 사고의 깊이와 비판적 태도가 더 선명하게 드러납니다.",
    },
    {
        "id": "stakeholder-interview",
        "type": "interest",
        "title": "{stakeholder} 인터뷰로 보는 {ethical_conflict}의 실제 쟁점",
        "reason": "자료 조사에 학생 의견과 현장성을 더해, 보고서가 추상적인 주장으로 흐르는 것을 막아줍니다.",
    },
    {
        "id": "future-reframe",
        "type": "major",
        "title": "{major} 최신 이슈를 고교 수준의 {method} 방식으로 재구성하기: {anchor}",
        "reason": "최신 전공 이슈를 무리하게 따라가기보다 학교 안 근거와 학생 수준의 방법으로 안전하게 재해석합니다.",
    },
)


def _build_topic_library() -> list[TopicExample]:
    topics: list[TopicExample] = []
    for domain_index, domain in enumerate(_DOMAIN_SEEDS, start=1):
        for angle_index, angle in enumerate(_ANGLE_TEMPLATES, start=1):
            topic_id = f"{domain['id']}-{angle['id']}"
            label = angle["title"].format(**domain)
            reason = angle["reason"].format(**domain)
            topics.append(
                TopicExample(
                    id=topic_id,
                    label=label[:118],
                    suggestion_type=angle["type"],  # type: ignore[typeddict-item]
                    reason=reason,
                    subject=domain["subject"],
                    major=domain["major"],
                    keywords=[
                        domain["subject"],
                        domain["major"],
                        domain["anchor"],
                        domain["core_concept"],
                        domain["social_issue"],
                        domain["method"],
                    ],
                )
            )
    return _dedupe_topics(topics)


def _dedupe_topics(topics: Iterable[TopicExample]) -> list[TopicExample]:
    result: list[TopicExample] = []
    seen_labels: set[str] = set()
    for topic in topics:
        label = topic.get("label", "").strip()
        if not label or label in seen_labels:
            continue
        seen_labels.add(label)
        result.append(topic)
    return result


TOPIC_LIBRARY: list[TopicExample] = _build_topic_library()
MIN_TOPIC_LIBRARY_SIZE = 300


def get_library_recommendations(subject: str, limit: int = 5) -> list[TopicExample]:
    query = subject.strip().lower()
    if not query:
        return TOPIC_LIBRARY[:limit]
    matches = [
        topic
        for topic in TOPIC_LIBRARY
        if query in " ".join(
            [
                topic.get("label", ""),
                topic.get("reason", ""),
                topic.get("subject", ""),
                topic.get("major", ""),
                " ".join(topic.get("keywords", [])),
            ]
        ).lower()
    ]
    return (matches or TOPIC_LIBRARY)[:limit]
