import React, { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import {
  Bot,
  ChevronDown,
  ChevronUp,
  Download,
  FileText,
  Loader2,
  Save,
  Send,
  Sparkles,
  ToggleLeft,
  ToggleRight,
  User,
  WandSparkles,
  ExternalLink,
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';
import { useLocation, useParams, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import confetti from 'canvas-confetti';
import { auth } from '../lib/firebase';
import { api, resolveApiBaseUrl } from '../lib/api';
import { cn } from '../lib/cn';
import { saveArchiveItem } from '../lib/archiveStore';
import { readQuestStart } from '../lib/questStart';
import { AdvancedPreview } from '../components/AdvancedPreview';
import { ReferenceSearchPanel } from '../components/ReferenceSearchPanel';
import { EvidenceDrawer } from '../components/EvidenceDrawer';
import { SuggestionReviewModal } from '../components/SuggestionReviewModal';
import {
  EmptyState,
  PageHeader,
  PrimaryButton,
  SecondaryButton,
  SectionCard,
  StatusBadge,
  SurfaceCard,
  WorkflowNotice,
} from '../components/primitives';
import {
  ensureThreeSuggestions,
  type GuidedTopicSelectionResponse,
  type GuidedTopicSuggestion,
  type GuidedTopicSuggestionResponse,
} from '../lib/guidedChat';

const MemoizedMarkdown = memo(function MemoizedMarkdown({
  content,
  role = 'foli',
}: {
  content: string;
  role?: MessageRole | 'document';
}) {
  const isUserMessage = role === 'user';

  return (
    <div
      className={cn(
        "prose prose-slate max-w-none text-sm leading-relaxed",
        isUserMessage ? "prose-invert text-white" : "text-slate-900"
      )}
    >
      <ReactMarkdown
        remarkPlugins={[remarkMath]}
        rehypePlugins={[rehypeKatex]}
        components={{
        h3: ({ children, ...props }) => {
          const text = React.Children.toArray(children).join('');
          const isAISuggestion = !isUserMessage && (text.includes('[AI 제안 초안]') || text.includes('[AI Draft Suggestion]'));

          if (isAISuggestion) {
            return (
              <h3
                {...props}
                className="mb-4 mt-8 flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-sm font-bold text-blue-800"
              >
                <span className="inline-flex h-5 w-5 items-center justify-center rounded-lg bg-blue-600 text-[10px] font-black text-white">AI</span>
                {children}
              </h3>
            );
          }

          return <h3 {...props} className={cn('mb-3 mt-6 text-lg font-black', isUserMessage ? 'text-white' : 'text-slate-900')} />;
        },
        p: ({ children, ...props }) => {
          const text = React.Children.toArray(children).join('');
          const isAINote =
            !isUserMessage && (text.includes('Foli가 생성한 제안 문장입니다') || text.includes('This text was generated by Foli'));

          if (isAINote) {
            return (
              <p
                {...props}
                className="mb-5 rounded-lg border-l-4 border-blue-300 bg-blue-50 px-3 py-2 text-sm font-medium italic text-slate-700"
              />
            );
          }

          return <p {...props} className={cn('text-[15px] leading-7 font-medium', isUserMessage ? 'whitespace-pre-wrap text-white' : 'text-slate-800')} />;
        },
        ul: ({ children, ...props }) => <ul {...props} className={cn("mb-4 ml-4 list-disc space-y-2", isUserMessage ? "text-white/90" : "text-slate-700")}>{children}</ul>,
        ol: ({ children, ...props }) => <ol {...props} className={cn("mb-4 ml-4 list-decimal space-y-2", isUserMessage ? "text-white/90" : "text-slate-700")}>{children}</ol>,
        li: ({ children, ...props }) => <li {...props} className="text-sm leading-relaxed">{children}</li>,
        code: ({ className, children, ...props }) => {
          const match = /language-(\w+)/.exec(className || '');
          const isInline = !match;
          return isInline ? (
            <code {...props} className="rounded bg-slate-200 px-1.5 py-0.5 font-mono text-xs font-bold text-blue-700">
              {children}
            </code>
          ) : (
            <pre className="mt-2 overflow-x-auto rounded-xl bg-slate-900 p-4">
              <code {...props} className={cn('font-mono text-xs text-slate-200', className)}>
                {children}
              </code>
            </pre>
          );
        },
        strong: ({ children }) => <strong className={cn("font-bold", isUserMessage ? "text-white" : "text-blue-900")}>{children}</strong>,
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
});

export type QualityLevel = 'low' | 'mid' | 'high';
type MessageRole = 'user' | 'foli' | 'assistant' | 'bot';

interface Message {
  id: string;
  role: MessageRole;
  content: string;
  suggestedContent?: string;
  topicSubject?: string;
  topicSuggestions?: GuidedTopicSuggestion[];
}

interface DraftArtifact {
  id: string;
  report_markdown: string;
  visual_specs: any[];
  math_expressions: any[];
  evidence_map?: Record<string, any> | null;
}

interface WorkshopSessionResponse {
  id: string;
  project_id: string;
  quest_id: string | null;
  status: string;
  quality_level: QualityLevel;
  turns?: Array<{
    id: string;
    turn_type: string;
    speaker_role?: string;
    query?: string;
    response?: string;
  }>;
}

interface WorkshopStateResponse {
  session: WorkshopSessionResponse;
  starter_choices: unknown[];
  followup_choices: unknown[];
  message: string | null;
  latest_artifact: DraftArtifact | null;
}

interface GuidedChatStartResponse {
  greeting: string;
  project_id: string | null;
  evidence_gap_note: string | null;
  limited_mode?: boolean | null;
  limited_reason?: string | null;
  state_summary?: Record<string, unknown> | null;
}

interface StreamMetaPayload {
  profile?: string;
  limited_mode?: boolean;
  limited_reason?: string | null;
}

const QUALITY_META_MAP: Record<QualityLevel, { label: string; status: 'success' | 'active' | 'warning' }> = {
  low: { label: '빠른 응답', status: 'success' },
  mid: { label: '균형 모드', status: 'active' },
  high: { label: '심화 모드', status: 'warning' },
};

const AI_SUGGESTION_HEADER = '### [AI 제안 초안]';
const LEGACY_AI_SUGGESTION_HEADER = '### [AI Draft Suggestion]';
const AI_SUGGESTION_NOTE =
  '> 반영 전 검토해 주세요. 이 문장은 Uni Foli가 생성한 제안 문장입니다. 수정 후 승인하기 전까지 학생 작성본으로 간주되지 않습니다.';
const LEGACY_AI_SUGGESTION_NOTE =
  '> Review before keeping. This text was generated by Uni Foli and is not student-authored until you edit and accept it.';
const GUIDED_CHAT_GREETING = '안녕하세요. 어떤 주제의 보고서를 써볼까요?';

function normalizeGuidedSuggestions(response: GuidedTopicSuggestionResponse): GuidedTopicSuggestion[] {
  return ensureThreeSuggestions(response).suggestions.slice(0, 3);
}

function formatGuidedSuggestionMessage(response: GuidedTopicSuggestionResponse) {
  const suggestions = normalizeGuidedSuggestions(response);
  const lines = [
    `요청하신 '${response.subject}' 주제 기준으로 3가지 방향을 제안드립니다.`,
    '',
    ...suggestions.flatMap((item, index) => {
      const chunk = [
        `${index + 1}. **${item.title}**`,
        `- 적합 이유: ${item.why_fit_student}`,
        `- 기록 연결: ${item.link_to_record_flow}`,
      ];
      if (item.link_to_target_major_or_university) {
        chunk.push(`- 목표 연결: ${item.link_to_target_major_or_university}`);
      }
      if (item.caution_note) {
        chunk.push(`- 주의: ${item.caution_note}`);
      }
      return chunk;
    }),
  ];
  if (response.evidence_gap_note) {
    lines.push('', `참고: ${response.evidence_gap_note}`);
  }
  lines.push('', '아래 카드에서 한 가지를 선택해 주세요.');
  return lines.join('\n');
}

function formatGuidedSelectionMessage(response: GuidedTopicSelectionResponse) {
  const lines = [
    `선택하신 주제는 **${response.selected_title}**입니다.`,
    '',
    response.guidance_message,
    '',
    '권장 분량:',
    ...response.recommended_page_ranges.map(
      range => `- ${range.label} (${range.min_pages}~${range.max_pages}p): ${range.why_this_length}`,
    ),
    '',
    '권장 개요:',
    ...response.recommended_outline.map(section => `- ${section.title}: ${section.purpose}`),
    '',
    '오른쪽 초안 패널에 스타터 초안을 채워 두었습니다. 다음 메시지로 세부 문단을 이어가 보세요.',
  ];
  return lines.join('\n');
}

function resolveGuidedSelectionFromText(text: string, suggestions: GuidedTopicSuggestion[]): GuidedTopicSuggestion | null {
  if (!suggestions.length) {
    return null;
  }
  const normalized = text.trim().toLowerCase();
  if (!normalized) {
    return null;
  }
  const numberMatch = normalized.match(/^([1-3])(?:번(?:으로|으로 진행|으로 해줘)?)?$/);
  if (numberMatch) {
    const index = Number(numberMatch[1]) - 1;
    return suggestions[index] ?? null;
  }
  const topicIdMatch = normalized.match(/^topic-([1-3])$/);
  if (topicIdMatch) {
    const index = Number(topicIdMatch[1]) - 1;
    return suggestions[index] ?? null;
  }
  return (
    suggestions.find(
      item =>
        normalized === item.id.toLowerCase() ||
        normalized === item.title.toLowerCase() ||
        normalized.includes(item.title.toLowerCase()),
    ) ?? null
  );
}

function buildFoliFallback(message: string) {
  const clean = message.toLowerCase().trim();
  const greetings = ['안녕', '반가워', '하이', '안녕하세요', 'hello', 'hi', 'hey'];

  if (greetings.some(token => clean.includes(token))) {
    return [
      '안녕하세요. Uni Foli 워크숍입니다.',
      '',
      '현재 일부 고급 기능이 제한되어 있어도, 초안 구조화와 문장 개선은 계속 도와드릴 수 있습니다.',
    ].join('\n');
  }

  return [
    '현재 연결 문제로 자동 근거 검증이 제한되어 있습니다.',
    '',
    '대신 아래 작업은 바로 도와드릴 수 있어요:',
    '1. 연구 질문 구체화',
    '2. 필요한 근거 목록 정리',
    '3. 보고서 구조 설계',
  ].join('\n');
}

async function streamFoliReply(
  projectId: string | undefined,
  workshopId: string | undefined,
  message: string,
  onDelta?: (delta: string) => void,
  onMeta?: (meta: StreamMetaPayload) => void,
) {
  const baseUrl = resolveApiBaseUrl();
  const token = auth?.currentUser ? await auth.currentUser.getIdToken() : null;
  let response: Response;

  try {
    if (workshopId) {
      response = await fetch(`${baseUrl}/api/v1/workshops/${workshopId}/chat/stream`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
        body: JSON.stringify({ message }),
      });
    } else {
      response = await fetch(`${baseUrl}/api/v1/drafts/chat/stream`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
        body: JSON.stringify({ project_id: projectId, message, reference_materials: [] }),
      });
    }
  } catch {
    if (!projectId && !workshopId) return buildFoliFallback(message);
    throw new Error('NETWORK_FAIL');
  }

  if (!response.ok || !response.body) {
    if (!projectId && !workshopId) return buildFoliFallback(message);
    if (response.status === 429) throw new Error('RATE_LIMIT');
    if (response.status === 401 || response.status === 403) throw new Error('AUTH_REQUIRED');
    throw new Error('STREAM_FAIL');
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let full = '';
  let buffer = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const chunks = buffer.split('\n\n');
    buffer = chunks.pop() || '';

    for (const event of chunks) {
      const line = event.split('\n').find(item => item.startsWith('data:'));
      if (!line) continue;

      let payload: Record<string, unknown>;
      try {
        payload = JSON.parse(line.replace(/^data:\s*/, ''));
      } catch {
        continue;
      }

      if (payload.done) break;
      if (typeof payload.error === 'string' && payload.error.trim()) throw new Error(payload.error.trim());

      if (payload.meta && typeof payload.meta === 'object') {
        onMeta?.(payload.meta as StreamMetaPayload);
      }

      if (typeof payload.token === 'string' && payload.token) {
        full += payload.token;
        onDelta?.(payload.token);
      }
    }
  }

  return full.trim();
}

const ChatBubble = memo(function ChatBubble({
  message,
  onSuggestClick,
  onTopicSelect,
  selectingTopicId,
}: {
  message: Message;
  onSuggestClick: (content: string) => void;
  onTopicSelect: (topicId: string, subject: string) => void;
  selectingTopicId: string | null;
}) {
  const isUser = message.role === 'user';
  const isStreaming = !isUser && !message.content;

  return (
    <div className={cn("flex gap-3", isUser && "flex-row-reverse")}>
      <div
        className={cn(
          "flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl text-xs font-black shadow-sm transition-all",
          isUser ? 'bg-slate-100 text-slate-500' : 'bg-gradient-to-br from-blue-600 to-blue-700 text-white shadow-blue-100'
        )}
      >
        {isUser ? <User size={18} /> : <Bot size={18} />}
      </div>

      <div
        className={cn(
          "relative max-w-[88%] rounded-2xl border px-4 py-3.5 shadow-sm transition-all duration-300 sm:max-w-[80%]",
          isUser 
            ? 'border-blue-700 bg-blue-600 text-white shadow-md shadow-blue-100/50' 
            : 'border-slate-200 bg-white text-slate-900 shadow-sm'
        )}
      >
        <div className="flex flex-col gap-1.5">
          {isUser ? (
            <p className="whitespace-pre-wrap text-[15px] font-medium leading-7 text-white">
              {String(message.content || '')}
            </p>
          ) : (
            <MemoizedMarkdown content={String(message.content || '')} role={message.role} />
          )}
          {isStreaming && (
            <div className="flex items-center gap-2 py-1 opacity-70">
              <Loader2 size={12} className="animate-spin text-blue-600" />
              <span className="text-[11px] font-bold text-slate-400">Uni Foli가 작성 중...</span>
            </div>
          )}
        </div>

        {message.suggestedContent ? (
          <SecondaryButton 
            size="sm" 
            className="mt-3 w-full border-blue-200 bg-blue-50 text-blue-700 hover:bg-blue-100 shadow-sm" 
            onClick={() => onSuggestClick(message.suggestedContent || '')}
          >
            <Sparkles size={14} className="mr-1.5" />
            제안 초안 검토
          </SecondaryButton>
        ) : null}

        {message.topicSuggestions?.length ? (
          <div className="mt-4 space-y-2.5">
            <p className="px-1 text-[10px] font-black uppercase tracking-widest text-slate-400">Foli의 추천 주제</p>
            {message.topicSuggestions.map((topic, index) => (
              <button
                key={topic.id}
                type="button"
                onClick={() => onTopicSelect(topic.id, message.topicSubject || '')}
                disabled={Boolean(selectingTopicId)}
                className="group w-full rounded-2xl border border-slate-100 bg-slate-50/80 p-3.5 text-left transition-all hover:border-blue-200 hover:bg-blue-50/50 hover:shadow-md disabled:cursor-not-allowed disabled:opacity-60"
              >
                <div className="flex items-center justify-between">
                  <span className="inline-flex items-center justify-center rounded-lg bg-white px-2.5 py-1 text-[10px] font-black text-slate-500 shadow-sm transition-colors group-hover:bg-blue-600 group-hover:text-white">
                    주제 {index + 1}
                  </span>
                  {selectingTopicId === topic.id && <Loader2 size={12} className="animate-spin text-blue-600" />}
                </div>
                <p className="mt-2.5 text-[15px] font-bold leading-tight text-slate-900 group-hover:text-blue-700">{topic.title}</p>
                <p className="mt-1.5 text-xs font-medium leading-relaxed text-slate-500">
                  {selectingTopicId === topic.id ? '선택한 주제로 초안 세션을 준비 중입니다...' : '클릭하면 워크숍 초안을 즉시 생성합니다.'}
                </p>
              </button>
            ))}
          </div>
        ) : null}
      </div>
    </div>
  );
});

export function Workshop() {
  const { projectId } = useParams<{ projectId: string }>();
  const location = useLocation();
  const navigate = useNavigate();

  const [workshopState, setWorkshopState] = useState<WorkshopStateResponse | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isSessionLoading, setIsSessionLoading] = useState(true);
  const [documentContent, setDocumentContent] = useState('');
  const [qualityLevel, setQualityLevel] = useState<QualityLevel>('mid');
  const [advancedMode, setAdvancedMode] = useState(false);
  const [renderArtifact, setRenderArtifact] = useState<DraftArtifact | null>(null);

  const [diagnosisReport, setDiagnosisReport] = useState<Record<string, unknown> | null>(null);
  const [showDiagnosis, setShowDiagnosis] = useState(false);
  const [isRendering, setIsRendering] = useState(false);
  const [pendingSuggestion, setPendingSuggestion] = useState<string | null>(null);
  const [guidedSubject, setGuidedSubject] = useState<string | null>(null);
  const [guidedSuggestions, setGuidedSuggestions] = useState<GuidedTopicSuggestion[]>([]);
  const [isGuidedTopicSelected, setIsGuidedTopicSelected] = useState(false);
  const [isSelectingGuidedTopicId, setIsSelectingGuidedTopicId] = useState<string | null>(null);
  const [chatMeta, setChatMeta] = useState<StreamMetaPayload | null>(null);
  const [mobileView, setMobileView] = useState<'chat' | 'draft'>('chat');
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const questStart = useMemo(() => readQuestStart(), []);
  const initialMajor = useMemo(() => ((location.state as { major?: string } | null)?.major || '미지정'), [location.state]);
  const isProjectBacked = Boolean(projectId && projectId !== 'demo');
  const guidedProjectId = isProjectBacked ? projectId ?? null : null;
  const fileName = useMemo(() => `${(questStart?.title || '초안').replace(/\s+/g, '_')}.hwpx`, [questStart]);

  const initWorkshop = useCallback(async () => {
    setIsSessionLoading(true);
    setGuidedSubject(null);
    setGuidedSuggestions([]);
    setIsGuidedTopicSelected(false);
    setIsSelectingGuidedTopicId(null);
    setChatMeta(null);
    try {
      const sessions = await api.get<WorkshopSessionResponse[]>(`/api/v1/workshops?project_id=${projectId}`);
      const active = sessions.find(session => session.status !== 'completed');
      const preferredQuality = localStorage.getItem('uni_foli_quality_level');
      const createQuality: QualityLevel =
        preferredQuality === 'low' || preferredQuality === 'mid' || preferredQuality === 'high'
          ? preferredQuality
          : 'mid';
      const state = active
        ? await api.get<WorkshopStateResponse>(`/api/v1/workshops/${active.id}`)
        : await api.post<WorkshopStateResponse>('/api/v1/workshops', { project_id: projectId, quality_level: createQuality });

      setWorkshopState(state);
      setQualityLevel(state.session.quality_level);

      if (state.latest_artifact) {
        setRenderArtifact(state.latest_artifact);
        setDocumentContent(state.latest_artifact.report_markdown);
      }

      const turns = state.session.turns || [];
      const loadedMessages: Message[] = [];
      turns.forEach(turn => {
        const role: MessageRole = (turn.speaker_role === 'assistant' || turn.speaker_role === 'bot') ? 'foli' : 'user';
        const content = (role === 'foli' ? (turn.response || turn.query) : turn.query) || '';
        
        if (role === 'foli') {
          loadedMessages.push({ id: turn.id, role: 'foli', content });
        } else {
          loadedMessages.push({ id: turn.id, role: 'user', content });
          if (turn.response) {
            loadedMessages.push({ id: `${turn.id}-A`, role: 'foli', content: turn.response });
          }
        }
      });

      if (loadedMessages.length) {
        setMessages(loadedMessages);
        setIsGuidedTopicSelected(true);
      } else {
        try {
          const guidedStart = await api.post<GuidedChatStartResponse>('/api/v1/guided-chat/start', {
            project_id: projectId,
          });
          const greeting = (guidedStart.greeting || GUIDED_CHAT_GREETING).trim();
          const greetingMessage = guidedStart.evidence_gap_note ? `${greeting}\n\n${guidedStart.evidence_gap_note}` : greeting;
          const stateSummary = guidedStart.state_summary || {};
          const cachedStarter =
            typeof stateSummary.starter_draft_markdown === 'string' && stateSummary.starter_draft_markdown.trim()
              ? stateSummary.starter_draft_markdown
              : null;
          const cachedSubject =
            typeof stateSummary.subject === 'string' && stateSummary.subject.trim()
              ? stateSummary.subject
              : null;
          const cachedSelectedTopic =
            typeof stateSummary.selected_topic === 'string' && stateSummary.selected_topic.trim()
              ? stateSummary.selected_topic
              : null;

          if (guidedStart.limited_mode) {
            setChatMeta({
              profile: 'standard',
              limited_mode: true,
              limited_reason: guidedStart.limited_reason || 'limited_context',
            });
          }
          if (cachedSubject) {
            setGuidedSubject(cachedSubject);
          }
          if (cachedStarter && !state.latest_artifact) {
            setDocumentContent(cachedStarter);
            setIsGuidedTopicSelected(true);
            setMessages([
              { id: 'init', role: 'foli', content: greetingMessage },
              {
                id: 'guided-resume',
                role: 'foli',
                content: cachedSelectedTopic
                  ? `저장된 주제 '${cachedSelectedTopic}' 초안을 불러왔습니다. 이어서 보강해 보세요.`
                  : '저장된 초안을 불러왔습니다. 이어서 보강해 보세요.',
              },
            ]);
          } else {
            setMessages([{ id: 'init', role: 'foli', content: greetingMessage }]);
          }
        } catch {
          setMessages([{ id: 'init', role: 'foli', content: GUIDED_CHAT_GREETING }]);
        }
      }

      api.get<{ result_payload?: Record<string, unknown> }>(`/api/v1/diagnosis/project/${projectId}/latest`)
        .then(res => {
          if (res?.result_payload) {
            setDiagnosisReport(res.result_payload);
            setShowDiagnosis(true);
          }
        })
        .catch(() => {});
    } catch (error) {
      console.error('Workshop init failed:', error);
      toast.error('워크숍을 불러오지 못했습니다. 로컬 모드로 전환합니다.');
      setIsGuidedTopicSelected(true);
      setMessages([{ id: 'fallback', role: 'foli', content: '세션 연결에 실패했습니다. 로컬에서 초안 작성을 진행하실 수 있습니다.' }]);
    } finally {
      setIsSessionLoading(false);
    }
  }, [projectId]);

  useEffect(() => {
    const savedLevel = localStorage.getItem('uni_foli_quality_level');
    if (savedLevel === 'low' || savedLevel === 'mid' || savedLevel === 'high') {
      setQualityLevel(savedLevel as QualityLevel);
    }
    if (!documentContent) {
      setDocumentContent(
        questStart?.document_seed_markdown || `# [연구 초안] ${questStart?.title || '새 주제'}\n\n**전공:** ${initialMajor}\n\n## 1. 연구 동기`,
      );
    }

    if (isProjectBacked) {
      void initWorkshop();
    } else {
      setIsSessionLoading(false);
      setIsGuidedTopicSelected(true);
      setMessages([{ id: 'demo-init', role: 'foli', content: '데모 모드입니다. Uni Foli에게 질문하면 초안 작성을 도와드립니다.' }]);
    }
  }, [initialMajor, isProjectBacked, initWorkshop]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  useEffect(() => {
    if (!workshopState?.session.id || !documentContent) return;
    const timeout = setTimeout(() => {
      api.put(`/api/v1/workshops/${workshopState.session.id}/drafts/latest`, { document_content: documentContent })
        .catch(err => console.error('Autosave failed:', err));
    }, 3000);
    return () => clearTimeout(timeout);
  }, [documentContent, workshopState?.session.id]);

  useEffect(() => {
    if (!documentContent.includes('### [AI')) return;
    const normalizedMarker = documentContent
      .replace(/### \[AI[^\]]*\]/g, AI_SUGGESTION_HEADER)
      .replace(LEGACY_AI_SUGGESTION_HEADER, AI_SUGGESTION_HEADER)
      .replace(LEGACY_AI_SUGGESTION_NOTE, AI_SUGGESTION_NOTE);
    const final = normalizedMarker.includes(AI_SUGGESTION_NOTE)
      ? normalizedMarker
      : normalizedMarker.replace(AI_SUGGESTION_HEADER, `${AI_SUGGESTION_HEADER}\n${AI_SUGGESTION_NOTE}`);
    if (final !== documentContent) setDocumentContent(final);
  }, [documentContent]);


  const handleGuidedTopicSelection = useCallback(
    async (topicId: string, subjectFromMessage?: string) => {
      if (!guidedSuggestions.length || !guidedProjectId) return;

      setIsSelectingGuidedTopicId(topicId);
      try {
        const response = await api.post<GuidedTopicSelectionResponse>('/api/v1/guided-chat/topic-selection', {
          project_id: guidedProjectId,
          selected_topic_id: topicId,
          subject: subjectFromMessage || guidedSubject || undefined,
          suggestions: guidedSuggestions,
        });
        if (response.limited_mode) {
          setChatMeta({
            profile: 'fast',
            limited_mode: true,
            limited_reason: response.limited_reason || 'limited_context',
          });
        }
        setDocumentContent(response.starter_draft_markdown);
        setIsGuidedTopicSelected(true);
        setMessages(prev => [...prev, { id: crypto.randomUUID(), role: 'foli', content: formatGuidedSelectionMessage(response) }]);
        toast.success('선택한 주제 기준으로 프로젝트를 구성했습니다.');
      } catch (error) {
        console.error('Guided topic selection failed:', error);
        toast.error('주제 선택 반영에 실패했습니다.');
      } finally {
        setIsSelectingGuidedTopicId(null);
      }
    },
    [guidedProjectId, guidedSubject, guidedSuggestions],
  );

  const requestGuidedSuggestions = useCallback(
    async (subjectText: string) => {
      if (!guidedProjectId) return;
      const pendingId = crypto.randomUUID();
      setMessages(prev => [
        ...prev,
        {
          id: pendingId,
          role: 'foli',
          content: '주제 후보를 빠르게 정리하고 있습니다. 잠시만 기다려 주세요.',
        },
      ]);
      try {
        const response = await api.post<GuidedTopicSuggestionResponse>('/api/v1/guided-chat/topic-suggestions', {
          project_id: guidedProjectId,
          subject: subjectText,
        });
        const normalizedSuggestions = normalizeGuidedSuggestions(response);
        if (response.limited_mode) {
          setChatMeta({
            profile: 'fast',
            limited_mode: true,
            limited_reason: response.limited_reason || 'limited_context',
          });
        }
        setGuidedSubject(response.subject);
        setGuidedSuggestions(normalizedSuggestions);
        setMessages(prev => [
          ...prev.map(message =>
            message.id === pendingId
              ? {
                  ...message,
                  content: formatGuidedSuggestionMessage(response),
                  topicSubject: response.subject,
                  topicSuggestions: normalizedSuggestions,
                }
              : message,
          ),
        ]);
      } catch (error) {
        setMessages(prev => prev.filter(message => message.id !== pendingId));
        throw error;
      }
    },
    [guidedProjectId],
  );

  const handleSend = async (overriddenText?: string) => {
    const text = (overriddenText ?? input).trim();
    if (!text || isTyping || isSelectingGuidedTopicId) return;
    if (!overriddenText) setInput('');

    setMessages(prev => [...prev, { id: crypto.randomUUID(), role: 'user', content: text }]);

    if (isProjectBacked && !isGuidedTopicSelected) {
      const selectedFromText = resolveGuidedSelectionFromText(text, guidedSuggestions);
      if (selectedFromText) {
        await handleGuidedTopicSelection(selectedFromText.id, guidedSubject || undefined);
        return;
      }

      setIsTyping(true);
      try {
        await requestGuidedSuggestions(text);
      } catch (error) {
        console.error('Guided suggestion failed:', error);
        toast.error('주제 제안 생성에 실패했습니다.');
      } finally {
        setIsTyping(false);
      }
      return;
    }

    setIsTyping(true);
    setChatMeta(null);

    const foliId = crypto.randomUUID();
    setMessages(prev => [...prev, { id: foliId, role: 'foli', content: '' }]);

    let accumulated = '';
    let pendingDelta = '';
    let flushTimer: number | null = null;

    const flushBufferedDelta = () => {
      if (!pendingDelta) {
        flushTimer = null;
        return;
      }
      accumulated += pendingDelta;
      pendingDelta = '';
      flushTimer = null;
      setMessages(prev => prev.map(message => (message.id === foliId ? { ...message, content: accumulated } : message)));
    };

    try {
      const raw = await streamFoliReply(
        isProjectBacked ? projectId : undefined,
        workshopState?.session.id,
        text,
        delta => {
          pendingDelta += delta;
          if (flushTimer === null) {
            flushTimer = window.setTimeout(flushBufferedDelta, 40);
          }
        },
        meta => {
          setChatMeta(meta);
        },
      );

      if (flushTimer !== null) {
        window.clearTimeout(flushTimer);
        flushTimer = null;
      }
      flushBufferedDelta();

      const tagMatch = raw.match(/\[CONTENT\]([\s\S]*?)\[\/CONTENT\]/);
      if (tagMatch) {
        const suggestionContent = tagMatch[1].trim();
        setMessages(prev =>
          prev.map(message =>
            message.id === foliId
              ? {
                  ...message,
                  content: raw.replace(/\[CONTENT\][\s\S]*?\[\/CONTENT\]/, '').trim(),
                  suggestedContent: suggestionContent,
                }
              : message,
          ),
        );
        applySuggestedContent(suggestionContent);
      } else {
        setMessages(prev =>
          prev.map(message =>
            message.id === foliId ? { ...message, content: raw || accumulated || '응답을 생성하지 못했습니다.' } : message,
          ),
        );
      }
    } catch (error) {
      console.error('AI reply stream failed:', error);
      toast.error('대화 중 오류가 발생했습니다.');
    } finally {
      setIsTyping(false);
    }
  };

  const applySuggestedContent = (content: string) => {
    if (documentContent.includes(content)) {
      setPendingSuggestion(null);
      return;
    }

    const marker = `${AI_SUGGESTION_HEADER}\n${AI_SUGGESTION_NOTE}`;
    const updated = `${documentContent}\n\n${marker}\n\n${content}`;

    setDocumentContent(updated);
    setPendingSuggestion(null);
    toast.success('제안 초안을 문서에 반영했습니다.');
  };

  const handleGenerateDraft = async () => {
    if (!workshopState || isRendering) return;
    setIsRendering(true);
    try {
      await api.post(`/api/v1/workshops/${workshopState.session.id}/render`);
      toast.success('결과물 생성을 요청했습니다.');
    } catch (error) {
      console.error('Failed to render draft:', error);
      toast.error('생성 요청에 실패했습니다.');
    } finally {
      setIsRendering(false);
    }
  };

  const handleSaveDraft = () => {
    saveArchiveItem({
      id: crypto.randomUUID(),
      projectId: projectId ?? null,
      title: fileName.replace('.hwpx', ''),
      subject: initialMajor,
      createdAt: new Date().toISOString(),
      contentMarkdown: documentContent,
    });
    toast.success('워크숍 초안을 저장했습니다.');
    confetti({ particleCount: 80, spread: 62, origin: { y: 0.65 } });
  };

  const handleUpdateVisualStatus = async (visualId: string, status: string) => {
    if (!workshopState?.session.id) return;
    try {
      await api.put(`/api/v1/workshops/${workshopState.session.id}/visuals/${visualId}/status`, { status });
      toast.success('상태를 업데이트했습니다.');
    } catch {
      toast.error('상태 업데이트 실패');
    }
  };

  const qualityMeta = QUALITY_META_MAP[qualityLevel];
  const diagnosisSummary = (diagnosisReport?.summary ?? {}) as {
    headline?: string;
    risk_level?: string;
    gaps?: unknown[];
  };
  const diagnosisHeadline = diagnosisSummary.headline;
  const diagnosisRisk = diagnosisSummary.risk_level;
  const diagnosisGapCount = diagnosisSummary.gaps?.length || 0;

  const inputPlaceholder = isProjectBacked && !isGuidedTopicSelected
    ? '관심 과목이나 주제를 입력해 주세요.'
    : '메시지를 입력하세요...';

  return (
    <div className={cn("mx-auto max-w-[1800px] space-y-4 px-2.5 py-3 transition-all duration-700 sm:space-y-6 sm:px-4 sm:py-6", advancedMode && "rounded-[32px] bg-blue-50/30 shadow-[inset_0_0_100px_rgba(37,99,235,0.03)] sm:rounded-[48px]")}>
      <motion.div
        animate={advancedMode ? { y: [0, -2, 0] } : {}}
        transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
      >
        <PageHeader
          eyebrow="워크숍"
          title="Uni Foli 초안 워크스페이스"
          description="Uni Foli와 대화하며 나만의 연구 초안을 완성해 보세요."
          actions={
            <div className="flex items-center gap-2">
              <SecondaryButton
                data-testid="workshop-advanced-toggle"
                onClick={() => setAdvancedMode(prev => !prev)}
                aria-label={advancedMode ? '고급 모드 끄기' : '고급 모드 켜기'}
              >
                {advancedMode ? <ToggleRight size={16} /> : <ToggleLeft size={16} />}
                {advancedMode ? '고급 모드' : '기본 모드'}
              </SecondaryButton>
              <PrimaryButton onClick={handleGenerateDraft} disabled={!workshopState || isRendering}>
                {isRendering ? <Loader2 size={16} className="animate-spin" /> : <WandSparkles size={16} />}
                결과물 생성
              </PrimaryButton>
            </div>
          }
          evidence={
            <div className="flex flex-wrap items-center gap-2">
              <StatusBadge status={isProjectBacked ? 'success' : 'warning'}>{isProjectBacked ? '프로젝트 연동' : '데모 모드'}</StatusBadge>
              {isProjectBacked && (
                <StatusBadge status={isGuidedTopicSelected ? 'success' : 'warning'}>
                  {isGuidedTopicSelected ? '주제 선정됨' : '주제 대기'}
                </StatusBadge>
              )}
              <StatusBadge status={qualityMeta.status}>{qualityMeta.label}</StatusBadge>
            </div>
          }
        />

        <SuggestionReviewModal
          isOpen={Boolean(pendingSuggestion)}
          content={pendingSuggestion}
          onApply={() => pendingSuggestion && applySuggestedContent(pendingSuggestion)}
          onCancel={() => setPendingSuggestion(null)}
        />

        <div className="mt-6 lg:hidden">
          <div className="inline-flex w-full items-center gap-1 rounded-2xl border border-slate-200 bg-white p-1 shadow-sm">
            <button
              type="button"
              onClick={() => setMobileView('chat')}
              className={cn(
                'h-10 flex-1 rounded-xl px-3 text-sm font-bold transition-all',
                mobileView === 'chat' ? 'bg-blue-600 text-white shadow-md' : 'text-slate-600 hover:bg-slate-50',
              )}
            >
              대화
            </button>
            <button
              type="button"
              onClick={() => setMobileView('draft')}
              className={cn(
                'h-10 flex-1 rounded-xl px-3 text-sm font-bold transition-all',
                mobileView === 'draft' ? 'bg-blue-600 text-white shadow-md' : 'text-slate-600 hover:bg-slate-50',
              )}
            >
              문서
            </button>
          </div>
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-[400px_minmax(0,1fr)] xl:grid-cols-[460px_minmax(0,1fr)]">
          <SectionCard
            title="Uni Foli 대화"
            eyebrow="Chat"
            className={cn(
              'flex min-h-0 flex-col h-[calc(100dvh-15rem)] min-h-[520px] max-h-[800px]',
              mobileView !== 'chat' && 'hidden lg:flex'
            )}
            bodyClassName="relative flex min-h-0 flex-1 flex-col overflow-hidden p-0"
          >
            <div className="flex h-full flex-col">
              <div className="flex-1 overflow-y-auto px-4 py-4 space-y-6 scroll-smooth">
                {diagnosisReport && (
                  <SurfaceCard tone="muted" padding="none" className="mb-4 overflow-hidden border-blue-100 bg-blue-50/30">
                    <button
                      type="button"
                      onClick={() => setShowDiagnosis(prev => !prev)}
                      className="flex w-full items-center justify-between px-4 py-3 text-left text-sm font-bold text-slate-700 hover:bg-blue-50/50"
                    >
                      <span className="inline-flex items-center gap-2">
                        <Sparkles size={15} className="text-blue-600" />
                        최근 생기부 진단 정보
                      </span>
                      {showDiagnosis ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                    </button>
                    <AnimatePresence>
                      {showDiagnosis && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          className="overflow-hidden border-t border-blue-100 px-4 pb-4"
                        >
                          <SurfaceCard padding="sm" className="mt-3 space-y-2 border-none bg-white/60">
                            <p className="text-sm font-bold text-slate-900">{diagnosisHeadline}</p>
                            <div className="flex flex-wrap items-center gap-2">
                              {diagnosisRisk && <StatusBadge status={diagnosisRisk === 'safe' ? 'success' : 'warning'}>{diagnosisRisk}</StatusBadge>}
                              <StatusBadge status="neutral">보완 {diagnosisGapCount}</StatusBadge>
                            </div>
                          </SurfaceCard>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </SurfaceCard>
                )}

                {chatMeta?.limited_mode && (
                  <WorkflowNotice
                    tone="warning"
                    title="임시 코칭 모드로 안내 중입니다"
                    description="모델 연결이 일시적으로 불안정해도 대화는 계속 진행됩니다. 요청하신 작업을 이어서 도와드릴게요."
                    className="mb-4"
                  />
                )}

                {isProjectBacked && !isGuidedTopicSelected && (
                  <WorkflowNotice
                    tone="info"
                    title="주제 선정이 필요합니다"
                    description="관심 있는 분야를 입력해 주세요."
                    className="mb-4"
                  />
                )}

                {!isSessionLoading ? (
                  <div className="space-y-6 pb-4">
                    {messages.map((message) => (
                      <ChatBubble
                        key={message.id}
                        message={message}
                        onSuggestClick={(content) => setPendingSuggestion(content)}
                        onTopicSelect={handleGuidedTopicSelection}
                        selectingTopicId={isSelectingGuidedTopicId}
                      />
                    ))}
                    <div ref={messagesEndRef} />
                  </div>
                ) : (
                  <div className="flex h-full items-center justify-center py-20">
                    <Loader2 size={24} className="animate-spin text-blue-600" />
                  </div>
                )}
              </div>

              <div className="border-t border-slate-100 bg-white p-4">
                <div className="flex items-center gap-3">
                  <input
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' && !e.shiftKey) {
                        e.preventDefault();
                        void handleSend();
                      }
                    }}
                    placeholder={inputPlaceholder}
                    disabled={isTyping || !!isSelectingGuidedTopicId}
                    className="flex-1 h-12 rounded-2xl border-2 border-slate-200 bg-slate-50 px-4 text-[15px] font-medium text-slate-900 outline-none transition-all placeholder:text-slate-400 focus:border-blue-500 disabled:opacity-50"
                  />
                  <button
                    type="button"
                    onClick={() => void handleSend()}
                    disabled={!input.trim() || isTyping || !!isSelectingGuidedTopicId}
                    className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-600 text-white shadow-lg shadow-blue-100 transition-all hover:bg-blue-700 disabled:bg-slate-200"
                  >
                    {isTyping ? <Loader2 size={20} className="animate-spin" /> : <Send size={20} />}
                  </button>
                </div>
              </div>
            </div>
          </SectionCard>

          <SectionCard
            title="초안 문서"
            description="Uni Foli가 제안한 내용을 바탕으로 구성된 문서입니다. 자유롭게 수정하여 보관하세요."
            eyebrow="Drafting"
            className={cn(
              'flex min-h-0 flex-col h-[calc(100dvh-15rem)] min-h-[520px] max-h-[800px]',
              mobileView !== 'draft' && 'hidden lg:flex'
            )}
            bodyClassName="flex min-h-0 flex-1 flex-col overflow-hidden p-0"
            actions={
              <div className="flex items-center gap-2">
                <SecondaryButton size="sm" onClick={handleSaveDraft}>
                  <Save size={14} className="mr-1.5" />
                  저장
                </SecondaryButton>
                <SecondaryButton size="sm" onClick={() => {
                  const blob = new Blob([documentContent], { type: 'text/markdown' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = fileName.replace('.hwpx', '.md');
                  a.click();
                  URL.revokeObjectURL(url);
                }}>
                  <Download size={14} className="mr-1.5" />
                  다운로드
                </SecondaryButton>
              </div>
            }
          >
            <div className={cn("flex flex-1 flex-col overflow-hidden p-3 sm:p-4", advancedMode && "lg:flex-row gap-4")}>
              <textarea
                value={documentContent}
                onChange={(e) => setDocumentContent(e.target.value)}
                placeholder="Uni Foli와 대화하며 이곳에 초안을 채워보세요."
                className={cn(
                  "w-full flex-1 resize-none rounded-2xl border-none bg-slate-50 p-4 sm:p-6 text-[15px] sm:text-[16px] font-medium leading-relaxed text-slate-800 outline-none focus:bg-white focus:ring-4 focus:ring-blue-100/50 transition-all custom-scrollbar shadow-inner",
                  advancedMode && "lg:w-1/2"
                )}
              />
              
              {advancedMode ? (
                <div className="mt-4 flex flex-col gap-4 lg:mt-0 lg:w-1/2 overflow-y-auto pr-1 custom-scrollbar">
                  <EvidenceDrawer evidenceMap={renderArtifact?.evidence_map ?? null} />
                  <SurfaceCard className="p-4 border-blue-100 bg-blue-50/20 shadow-sm">
                    <AdvancedPreview
                      workshopId={workshopState?.session.id || ''}
                      artifactId={workshopState?.latest_artifact?.id || ''}
                      isAdvancedMode={advancedMode}
                      visualSpecs={renderArtifact?.visual_specs ?? []}
                      mathExpressions={renderArtifact?.math_expressions ?? []}
                      onUpdateVisualStatus={handleUpdateVisualStatus}
                    />
                  </SurfaceCard>
                </div>
              ) : null}
            </div>
          </SectionCard>
        </div>
      </motion.div>
    </div>
  );
}
