import React, { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import {
  Bot,
  ChevronDown,
  ChevronUp,
  Download,
  Loader2,
  PenSquare,
  Presentation,
  Save,
  Send,
  ToggleLeft,
  ToggleRight,
  User,
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import toast from 'react-hot-toast';
import confetti from 'canvas-confetti';
import { auth } from '../lib/firebase';
import { api, resolveApiBaseUrl } from '../lib/api';
import {
  ChatStreamError,
  consumeChatEventStream,
  openChatEventStream,
  resolveChatStreamFallbackHint,
  resolveChatStreamToastMessage,
  type ChatStreamMetaPayload,
} from '../lib/chatStream';
import { cn } from '../lib/cn';
import { saveArchiveItem } from '../lib/archiveStore';
import { readQuestStart } from '../lib/questStart';
import type { AuthTokenSource } from '../lib/requestAuth';
import { AdvancedPreview } from '../components/AdvancedPreview';
import { EvidenceDrawer } from '../components/EvidenceDrawer';
import {
  PageHeader,
  PrimaryButton,
  SecondaryButton,
  SectionCard,
  StatusBadge,
  SurfaceCard,
  WorkflowNotice,
} from '../components/primitives';
import { WorkshopProgress } from '../components/WorkshopProgress';
import {
  ensureThreeSuggestions,
  type GuidedChoiceGroup,
  type GuidedChoiceOption,
  type GuidedConversationPhase,
  type GuidedPageRangeSelectionResponse,
  type GuidedStructureOption,
  type GuidedStructureSelectionResponse,
  type GuidedTopicSelectionResponse,
  type GuidedTopicSuggestion,
  type GuidedTopicSuggestionResponse,
} from '../lib/guidedChat';
import {
  buildSpecificTopicCheckGroup,
  buildSubjectQuickPickGroup,
  inferGuidedPhase,
  isRecommendationAffirmative,
  isSpecificTopicAffirmative,
  isGuidedSetupComplete,
  looksLikeBroadSubject,
  resolvePageRangeLabel,
  resolveStructureOptionId,
} from '../lib/guidedConversation';
import {
  BLOCK_DEFINITIONS,
  WORKSHOP_MODE_OPTIONS,
  applyDraftPatch,
  createEmptyStructuredDraft,
  isPatchAcceptanceMessage,
  isSectionDraftIntent,
  markdownToStructuredDraft,
  normalizeStructuredDraft,
  structuredDraftToMarkdown,
  type WorkshopDraftAttribution,
  type WorkshopDraftPatchProposal,

  type WorkshopMode,
  type WorkshopStructuredDraftState,
} from '../lib/workshopCoauthoring';

const MemoizedMarkdown = memo(function MemoizedMarkdown({
  content,
  role = 'foli',
}: {
  content: string;
  role?: MessageRole | 'document';
}) {
  const isUserMessage = role === 'user';

  return (
    <div
      className={cn(
        "prose prose-slate max-w-none text-sm leading-relaxed",
        isUserMessage ? "prose-invert text-white" : "text-slate-900"
      )}
    >
      <ReactMarkdown
        remarkPlugins={[remarkMath]}
        rehypePlugins={[rehypeKatex]}
        components={{
        h3: ({ children, ...props }) => {
          const text = React.Children.toArray(children).join('');
          const isAISuggestion = !isUserMessage && (text.includes('[AI ?쒖븞 珥덉븞]') || text.includes('[AI Draft Suggestion]'));

          if (isAISuggestion) {
            return (
              <h3
                {...props}
                className="mb-4 mt-8 flex items-center gap-2 rounded-xl border border-[#004aad]/5 bg-[#004aad]/5 px-3 py-2 text-sm font-bold text-[#004aad]"
              >
                <span className="inline-flex h-5 w-5 items-center justify-center rounded-lg bg-[#004aad] text-[10px] font-black text-white">AI</span>
                {children}
              </h3>
            );
          }

          return <h3 {...props} className={cn('mb-3 mt-6 text-lg font-black', isUserMessage ? 'text-white' : 'text-slate-900')} />;
        },
        p: ({ children, ...props }) => {
          const text = React.Children.toArray(children).join('');
          const isAINote =
            !isUserMessage &&
            (
              text.includes('유니폴리가 생성한 제안 문장입니다.')
              || text.includes('AI 제안')
              || text.includes('This text was generated by Foli')
              || text.includes('AI suggestion')
            );

          if (isAINote) {
            return (
              <p
                {...props}
                className="mb-5 rounded-lg border-l-4 border-[#004aad]/20 bg-[#004aad]/5 px-3 py-2 text-sm font-medium italic text-slate-700"
              />
            );
          }

          return <p {...props} className={cn('text-[15px] leading-7 font-medium', isUserMessage ? 'whitespace-pre-wrap text-white' : 'text-slate-800')} />;
        },
        ul: ({ children, ...props }) => <ul {...props} className={cn("mb-4 ml-4 list-disc space-y-2", isUserMessage ? "text-white/90" : "text-slate-700")}>{children}</ul>,
        ol: ({ children, ...props }) => <ol {...props} className={cn("mb-4 ml-4 list-decimal space-y-2", isUserMessage ? "text-white/90" : "text-slate-700")}>{children}</ol>,
        li: ({ children, ...props }) => <li {...props} className="text-sm leading-relaxed">{children}</li>,
        code: ({ className, children, ...props }) => {
          const match = /language-(\w+)/.exec(className || '');
          const isInline = !match;
          return isInline ? (
            <code {...props} className="rounded bg-slate-100 px-1.5 py-0.5 font-mono text-xs font-bold text-[#004aad]">
              {children}
            </code>
          ) : (
            <pre className="mt-2 overflow-x-auto rounded-xl bg-slate-900 p-4">
              <code {...props} className={cn('font-mono text-xs text-slate-200', className)}>
                {children}
              </code>
            </pre>
          );
        },
        strong: ({ children }) => <strong className={cn("font-bold", isUserMessage ? "text-white" : "text-[#004aad]")}>{children}</strong>,
        }}
      >
        {content}
      </ReactMarkdown>
    </div>
  );
});

export type QualityLevel = 'low' | 'mid' | 'high';
type MessageRole = 'user' | 'foli' | 'assistant' | 'bot';

interface Message {
  id: string;
  role: MessageRole;
  content: string;
  draftPatch?: WorkshopDraftPatchProposal;
  phase?: GuidedConversationPhase | null;
  topicSubject?: string;
  topicSuggestions?: GuidedTopicSuggestion[];
  pageRangeOptions?: GuidedTopicSelectionResponse['recommended_page_ranges'];
  structureOptions?: GuidedStructureOption[];
  nextActionOptions?: GuidedChoiceOption[];
  choiceGroups?: GuidedChoiceGroup[];
}

interface DraftArtifact {
  id: string;
  report_markdown: string;
  visual_specs: any[];
  math_expressions: any[];
  evidence_map?: Record<string, any> | null;
  structured_draft?: WorkshopStructuredDraftState | null;
  updated_at?: string | null;
}

interface WorkshopSaveDraftResponse {
  status: string;
  message: string;
  saved_updated_at: string;
  structured_draft?: WorkshopStructuredDraftState | null;
}

interface WorkshopSessionResponse {
  id: string;
  project_id: string;
  quest_id: string | null;
  status: string;
  quality_level: QualityLevel;
  turns?: Array<{
    id: string;
    turn_type: string;
    speaker_role?: string;
    query?: string;
    response?: string;
    action_payload?: Record<string, unknown> | null;
  }>;
}

export interface QualityLevelInfo {
  level: QualityLevel;
  label: string;
  emoji: string;
  color: string;
  description: string;
  detail: string;
  student_fit: string;
  safety_posture: string;
  authenticity_policy: string;
  hallucination_guardrail: string;
  advanced_features_allowed: boolean;
  minimum_turn_count: number;
  minimum_reference_count: number;
  render_threshold: number;
}

export interface RenderRequirementInfo {
  required_context_score: number;
  minimum_turn_count: number;
  minimum_reference_count: number;
  current_context_score: number;
  current_turn_count: number;
  current_reference_count: number;
  can_render: boolean;
  missing: string[];
}

interface WorkshopStateResponse {
  session: WorkshopSessionResponse;
  starter_choices: any[];
  followup_choices: any[];
  message: string | null;
  quality_level_info?: QualityLevelInfo;
  available_quality_levels?: QualityLevelInfo[];
  render_requirements?: RenderRequirementInfo;
  latest_artifact: DraftArtifact | null;
}

interface GuidedChatStartResponse {
  greeting: string;
  assistant_message?: string | null;
  phase?: GuidedConversationPhase;
  project_id: string | null;
  evidence_gap_note: string | null;
  choice_groups?: GuidedChoiceGroup[];
  limited_mode?: boolean | null;
  limited_reason?: string | null;
  state_summary?: Record<string, unknown> | null;
}

interface StreamMetaPayload extends ChatStreamMetaPayload {
  coauthoring_mode?: WorkshopMode;
}

interface StreamFoliReplyResult {
  text: string;
  authSource: AuthTokenSource;
}

const QUALITY_META_MAP: Record<QualityLevel, { label: string; status: 'success' | 'active' | 'warning' }> = {
  low: { label: '鍮좊Ⅸ ?묐떟', status: 'success' },
  mid: { label: '洹좏삎 紐⑤뱶', status: 'active' },
  high: { label: '?ы솕 紐⑤뱶', status: 'warning' },
};

const GUIDED_CHAT_GREETING = '?덈뀞?섏꽭???대뼡 二쇱젣濡?蹂닿퀬?쒕? ?⑤낵源뚯슂?';
const DIAGNOSIS_RISK_LABEL_MAP: Record<string, string> = {
  safe: '洹쇨굅 異⑸텇',
  warning: '蹂댁셿 ?꾩슂',
  danger: '吏묒쨷 蹂댁셿 ?꾩슂',
};

function formatDiagnosisRiskLabel(value: string | undefined): string {
  const key = String(value || '').trim().toLowerCase();
  return DIAGNOSIS_RISK_LABEL_MAP[key] || '蹂댁셿 ?꾩슂';
}

function formatDraftAttributionLabel(attribution: WorkshopDraftAttribution): string {
  if (attribution === 'student-authored') return '?숈깮 ?묒꽦';
  if (attribution === 'ai-inserted-after-approval') return '?뱀씤 ??AI 諛섏쁺';
  return 'AI ?쒖븞';
}

function normalizeGuidedSuggestions(response: GuidedTopicSuggestionResponse): GuidedTopicSuggestion[] {
  return ensureThreeSuggestions(response).suggestions.slice(0, 3);
}

function formatGuidedSuggestionMessage(response: GuidedTopicSuggestionResponse) {
  const suggestions = normalizeGuidedSuggestions(response);
  const lines = [
    `???. '${response.subject}' ???? ?? ??? ??? ?? 3??? ?????.`,
    '',
    ...suggestions.flatMap((item, index) => {
      const chunk = [
        `${index + 1}. **${item.title}**`,
        `- ? ???: ${item.why_fit_student}`,
        `- ?? ??: ${item.link_to_record_flow}`,
      ];
      if (item.link_to_target_major_or_university) {
        chunk.push(`- ?? ??: ${item.link_to_target_major_or_university}`);
      }
      if (item.caution_note) {
        chunk.push(`- ??: ${item.caution_note}`);
      }
      return chunk;
    }),
  ];
  if (response.evidence_gap_note) {
    lines.push('', `??: ${response.evidence_gap_note}`);
  }
  lines.push('', '? ??? ?? ??? ??? ??? ?????.');
  return lines.join('\n');
}

function formatGuidedSelectionMessage(response: GuidedTopicSelectionResponse) {
  const lines = [
    `??? ??? **${response.selected_title}** ???.`,
    '',
    response.guidance_message,
    '',
    '??? ?? ??? ???? ?? ?? ??? ?????.',
  ];
  return lines.join('\n');
}

function formatGuidedPageRangeMessage(response: GuidedPageRangeSelectionResponse) {
  const lines = [
    response.assistant_message,
    '',
    `??? ??: **${response.selected_page_range_label}**`,
  ];
  if (response.selected_page_range_note) {
    lines.push(`- ??: ${response.selected_page_range_note}`);
  }
  lines.push('', '?? ?? ???? ??? ???.');
  return lines.join('\n');
}

function formatGuidedStructureMessage(response: GuidedStructureSelectionResponse) {
  return [
    response.assistant_message,
    '',
    `??? ??: **${response.selected_structure_label}**`,
    '',
    '???? ??? ???? ?? ??? ?? ??? ? ???.',
  ].join('\n');
}

function formatAssistantMessageWithEvidenceNote(
  assistantMessage: string | null | undefined,
  evidenceGapNote: string | null | undefined,
) {
  const base = (assistantMessage || '').trim();
  const note = (evidenceGapNote || '').trim();
  if (base && note) return `${base}\n\n??: ${note}`;
  if (base) return base;
  if (note) return `??: ${note}`;
  return GUIDED_CHAT_GREETING;
}

function buildTopicChoiceGroup(suggestions: GuidedTopicSuggestion[]): GuidedChoiceGroup {
  return {
    id: 'topic-selection',
    title: '이 중에서 가장 마음에 드는 주제를 골라주세요.',
    style: 'cards',
    options: suggestions.map((topic) => ({
      id: topic.id,
      label: topic.title,
      description: topic.why_fit_student,
      value: topic.id,
    })),
  };
}

function buildPageRangeChoiceGroup(
  pageRanges: GuidedTopicSelectionResponse['recommended_page_ranges'],
): GuidedChoiceGroup {
  return {
    id: 'page-range-selection',
    title: '보고서 분량을 선택해 주세요.',
    style: 'cards',
    options: pageRanges.map((range) => ({
      id: `page-range-${range.label}`,
      label: range.label,
      description: range.why_this_length,
      value: range.label,
    })),
  };
}

function buildStructureChoiceGroup(options: GuidedStructureOption[]): GuidedChoiceGroup {
  return {
    id: 'structure-selection',
    title: '구성 스타일을 골라주세요.',
    style: 'cards',
    options,
  };
}

function buildNextActionChoiceGroup(options: GuidedChoiceOption[]): GuidedChoiceGroup {
  return {
    id: 'next-action-selection',
    title: '다음으로 무엇을 할까요?',
    style: 'chips',
    options,
  };
}

function resolveGuidedSelectionFromText(text: string, suggestions: GuidedTopicSuggestion[]): GuidedTopicSuggestion | null {
  if (!suggestions.length) {
    return null;
  }
  const normalized = (text || '').trim().toLowerCase();
  if (!normalized) {
    return null;
  }
  const numberMatch = normalized.match(/^([1-3])$/);
  if (numberMatch) {
    const index = Number(numberMatch[1]) - 1;
    return suggestions[index] ?? null;
  }
  const topicIdMatch = normalized.match(/^topic-([1-3])$/);
  if (topicIdMatch) {
    const index = Number(topicIdMatch[1]) - 1;
    return suggestions[index] ?? null;
  }
  return (
    suggestions.find(
      item =>
        normalized === item.id.toLowerCase() ||
        normalized === item.title.toLowerCase() ||
        normalized.includes(item.title.toLowerCase()),
    ) ?? null
  );
}

function buildFoliFallback(message: string) {
  const clean = (message || '').toLowerCase().trim();
  const greetings = ['?덈뀞', 'hi', 'hello', 'hey', 'good morning', 'good evening'];

  if (greetings.some(token => clean.includes(token))) {
    return [
      '?덈뀞?섏꽭?? ?좊땲?대━ ?뚰겕???꾩슦誘몄엯?덈떎.',
      '',
      '?꾩옱 ?ㅼ떆媛?AI ?곌껐??遺덉븞?뺥븯吏留? 珥덉븞 援ъ“ ?뺣━? 臾몄옣 ?ㅻ벉湲곕뒗 怨꾩냽 ?꾩??쒕┫ ???덉뒿?덈떎.',
    ].join('\n');
  }

  return [
    '吏湲덉? ?먮룞 洹쇨굅 ?곌껐???쇱떆?곸쑝濡??쒗븳???곹깭?낅땲??',
    '',
    '?꾨옒 ?쒖꽌?濡?吏꾪뻾?섎㈃ ??붾? ?딄린吏 ?딄퀬 ?댁뼱媛????덉뒿?덈떎.',
    '1. ?대쾲 湲?먯꽌 ?듭떖?쇰줈 ?ㅻ０ 吏덈Ц????臾몄옣?쇰줈 ?뺣━?⑸땲??',
    '2. ?낅줈?쒗븳 湲곕줉?먯꽌 ?대? ?뺣낫??洹쇨굅瑜?2~3媛??곸뼱遊낅땲??',
    '3. ?꾩엯-蹂몃줎-寃곕줎 ?쒖꽌濡??⑤씫 堉덈?瑜?癒쇱? ?≪뒿?덈떎.',
  ].join('\n');
}

function normalizeStructuredDraftPatch(value: unknown): WorkshopDraftPatchProposal | null {
  if (!value || typeof value !== 'object') return null;
  const candidate = value as Record<string, unknown>;
  const mode = candidate.mode;
  const blockId = candidate.block_id;
  const content = String(candidate.content_markdown || '').trim();
  const requiresApproval = Boolean(candidate.requires_approval ?? true);
  if (
    (mode !== 'planning' && mode !== 'outline' && mode !== 'section_drafting' && mode !== 'revision') ||
    !(
      blockId === 'title' ||
      blockId === 'introduction_background' ||
      blockId === 'body_section_1' ||
      blockId === 'body_section_2' ||
      blockId === 'body_section_3' ||
      blockId === 'conclusion_reflection_next_step'
    ) ||
    !content
  ) {
    return null;
  }

  return {
    mode,
    block_id: blockId,
    heading: candidate.heading ? String(candidate.heading) : undefined,
    content_markdown: content,
    rationale: candidate.rationale ? String(candidate.rationale) : undefined,
    evidence_boundary_note: candidate.evidence_boundary_note ? String(candidate.evidence_boundary_note) : undefined,
    requires_approval: requiresApproval,
  };
}

function extractPatchTagFromRaw(raw: string): { cleaned: string; patch: WorkshopDraftPatchProposal | null } {
  if (!raw) return { cleaned: '', patch: null };
  const match = raw.match(/\[DRAFT_PATCH\]([\s\S]*?)\[\/DRAFT_PATCH\]/i);
  if (!match?.[1]) {
    return { cleaned: raw.trim(), patch: null };
  }
  let payload = match[1].trim();
  if (payload.startsWith('```')) {
    payload = payload.replace(/^```(?:json)?/i, '').replace(/```$/i, '').trim();
  }
  let patch: WorkshopDraftPatchProposal | null = null;
  try {
    patch = normalizeStructuredDraftPatch(JSON.parse(payload));
  } catch {
    patch = null;
  }
  const cleaned = raw.replace(/\[DRAFT_PATCH\][\s\S]*?\[\/DRAFT_PATCH\]/gi, '').trim();
  return { cleaned, patch };
}

async function streamFoliReply(
  projectId: string | undefined,
  workshopId: string | undefined,
  message: string,
  draftSnapshotMarkdown: string | undefined,
  mode: WorkshopMode,
  structuredDraft: WorkshopStructuredDraftState | null,
  onDelta?: (delta: string) => void,
  onMeta?: (meta: StreamMetaPayload) => void,
  onDraftPatch?: (patch: WorkshopDraftPatchProposal) => void,
): Promise<StreamFoliReplyResult> {
  const fallbackText = buildFoliFallback(message);
  const baseUrl = resolveApiBaseUrl();
  const endpoint = workshopId
    ? `${baseUrl}/api/v1/workshops/${workshopId}/chat/stream`
    : `${baseUrl}/api/v1/drafts/chat/stream`;
  const payload = workshopId
    ? {
        message,
        draft_snapshot_markdown: draftSnapshotMarkdown,
        mode,
        structured_draft: structuredDraft ?? undefined,
      }
    : {
        project_id: projectId,
        message,
        reference_materials: [],
        draft_snapshot_markdown: draftSnapshotMarkdown,
      };
  const { response, authSource } = await openChatEventStream({
    endpoint,
    payload,
    firebaseUser: auth?.currentUser,
  });

  const reader = response.body.getReader();
  const decoder = new TextDecoder('utf-8');
  let full = '';
  let buffer = '';
  let serverError: string | null = null;
  let streamDone = false;

  const extractPayloadsFromEvent = (eventChunk: string): Array<Record<string, unknown>> => {
    const dataLines = eventChunk
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.startsWith('data:'))
      .map((line) => line.replace(/^data:\s*/, ''));

    if (!dataLines.length) return [];

    const serialized = dataLines.join('\n').trim();
    if (!serialized) return [];

    try {
      const decoded = JSON.parse(serialized);
      return typeof decoded === 'object' && decoded !== null ? [decoded as Record<string, unknown>] : [];
    } catch {
      return [];
    }
  };

  const consumePayload = (payload: Record<string, unknown>) => {
    if (payload.done === true || payload.status === 'DONE') {
      streamDone = true;
      return;
    }

    if (typeof payload.error === 'string' && payload.error.trim()) {
      serverError = payload.error.trim();
      return;
    }

    if (payload.meta && typeof payload.meta === 'object') {
      onMeta?.(payload.meta as StreamMetaPayload);
    }

    if (payload.draft_patch && typeof payload.draft_patch === 'object') {
      onDraftPatch?.(payload.draft_patch as WorkshopDraftPatchProposal);
    }

    const tokenCandidate =
      typeof payload.token === 'string'
        ? payload.token
        : typeof payload.delta === 'string'
          ? payload.delta
          : null;

    if (tokenCandidate) {
      full += tokenCandidate;
      onDelta?.(tokenCandidate);
    }
  };

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const chunks = buffer.split('\n\n');
    buffer = chunks.pop() || '';

    for (const event of chunks) {
      const payloads = extractPayloadsFromEvent(event);
      for (const payload of payloads) {
        consumePayload(payload);
        if (streamDone || serverError) {
          break;
        }
      }
      if (streamDone || serverError) {
        break;
      }
    }

    if (streamDone || serverError) {
      break;
    }
  }

  // Flush decoder tail bytes to avoid partial UTF-8 character truncation on stream end.
  buffer += decoder.decode();
  if (buffer.trim()) {
    const chunks = buffer.split('\n\n');
    for (const event of chunks) {
      const payloads = extractPayloadsFromEvent(event);
      for (const payload of payloads) {
        consumePayload(payload);
        if (streamDone || serverError) {
          break;
        }
      }
      if (streamDone || serverError) {
        break;
      }
    }
  }

  if (serverError) {
    throw new ChatStreamError('stream_payload_error', `Chat stream payload returned an error: ${serverError}`, {
      endpoint,
      status: response.status,
      contentType: String(response.headers.get('content-type') || ''),
      detail: serverError,
      authSource,
    });
  }


  const normalized = full.trim();
  return { text: normalized || fallbackText, authSource };
}

const ChatBubble = memo(function ChatBubble({
  message,
  onApplyDraftPatch,
  onGuidedChoiceSelect,
  isGuidedActionLoading,
  selectingTopicId,
}: {
  message: Message;
  onApplyDraftPatch: (patch: WorkshopDraftPatchProposal) => void;
  onGuidedChoiceSelect: (groupId: string, option: GuidedChoiceOption, message: Message) => void;
  isGuidedActionLoading: boolean;
  selectingTopicId: string | null;
}) {
  const isUser = message.role === 'user';
  const isStreaming = !isUser && !message.content;
  const topicSuggestions = message.topicSuggestions ?? [];

  const interactiveGroups = useMemo(() => {
    const groups = [...(message.choiceGroups ?? [])];
    if (topicSuggestions.length > 0 && !groups.some((group) => group.id === 'topic-selection')) {
      groups.push({
        id: 'topic-selection',
        title: '이 중에서 가장 마음에 드는 주제를 골라주세요.',
        style: 'cards',
        options: topicSuggestions.map((topic) => ({
          id: topic.id,
          label: topic.title,
          description: topic.why_fit_student,
          value: topic.id,
        })),
      });
    }
    return groups;
  }, [message.choiceGroups, topicSuggestions]);

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className={cn('flex', isUser ? 'justify-end' : 'justify-start')}
    >
      <div
        className={cn(
          'max-w-[92%] rounded-2xl border px-4 py-3 shadow-sm',
          isUser
            ? 'border-[#004aad] bg-[#004aad] text-white'
            : 'border-slate-200 bg-white text-slate-900',
        )}
      >
        <div className="mb-2 flex items-center gap-2 text-xs font-black">
          {isUser ? <User size={14} /> : <Bot size={14} />}
          <span>{isUser ? '나' : '유니폴리'}</span>
        </div>

        {isStreaming ? (
          <div className="flex items-center gap-2 text-sm font-medium">
            <Loader2 size={14} className="animate-spin" />
            답변을 작성하고 있어요...
          </div>
        ) : message.content ? (
          <MemoizedMarkdown content={message.content} role={message.role} />
        ) : null}

        {message.draftPatch ? (
          <div className="mt-3 rounded-xl border border-[#004aad]/20 bg-[#004aad]/5 p-3">
            <p className="text-xs font-semibold text-slate-600">
              AI가 구조 초안을 제안했어요. 버튼을 누르면 문서에 반영됩니다.
            </p>
            <div className="mt-2">
              <PrimaryButton
                size="sm"
                onClick={() => onApplyDraftPatch(message.draftPatch!)}
              >
                제안 반영
              </PrimaryButton>
            </div>
          </div>
        ) : null}

        {interactiveGroups.length > 0 ? (
          <div className="mt-4 space-y-3">
            {interactiveGroups.map((group) => (
              <div key={group.id} className="rounded-xl border border-slate-200 bg-slate-50 p-3">
                <p className="text-xs font-black text-slate-600">{group.title}</p>
                <div
                  className={cn(
                    'mt-2',
                    group.style === 'chips' ? 'flex flex-wrap gap-2' : 'space-y-2',
                    group.style === 'buttons' ? 'grid gap-2 sm:grid-cols-2' : null,
                  )}
                >
                  {group.options.map((option) => {
                    const optionValue = String(option.value || option.id);
                    const isBusyTopic = group.id === 'topic-selection' && selectingTopicId === optionValue;
                    const disabled = isGuidedActionLoading || isBusyTopic;
                    return (
                      <button
                        key={`${group.id}:${option.id}`}
                        type="button"
                        onClick={() => onGuidedChoiceSelect(group.id, option, message)}
                        disabled={disabled}
                        className={cn(
                          'text-left transition-all disabled:opacity-60 disabled:cursor-not-allowed focus:outline-none focus-visible:ring-2 focus-visible:ring-[#004aad]/50',
                          group.style === 'chips'
                            ? 'rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-bold text-slate-700 hover:border-[#004aad] hover:text-[#004aad]'
                            : 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2 hover:border-[#004aad] hover:shadow-sm',
                        )}
                      >
                        <p className={cn(group.style === 'chips' ? 'text-xs font-bold' : 'text-sm font-bold text-slate-900')}>
                          {option.label}
                        </p>
                        {group.style !== 'chips' && option.description ? (
                          <p className="mt-1 text-xs text-slate-500">{option.description}</p>
                        ) : null}
                      </button>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        ) : null}
      </div>
    </motion.div>
  );
});
export function Workshop() {
  const navigate = useNavigate();
  const { projectId } = useParams<{ projectId: string }>();
  const location = useLocation();

  const [workshopState, setWorkshopState] = useState<WorkshopStateResponse | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isSessionLoading, setIsSessionLoading] = useState(true);
  const [documentContent, setDocumentContent] = useState('');
  const [qualityLevel, setQualityLevel] = useState<QualityLevel>('mid');
  const [advancedMode, setAdvancedMode] = useState(false);
  const [renderArtifact, setRenderArtifact] = useState<DraftArtifact | null>(null);
  const [latestDraftUpdatedAt, setLatestDraftUpdatedAt] = useState<string | null>(null);
  const [isDraftOutOfSync, setIsDraftOutOfSync] = useState(false);
  const [workshopMode, setWorkshopMode] = useState<WorkshopMode>('planning');
  const [showDraftControls, setShowDraftControls] = useState(false);
  const [showAdvancedTools, setShowAdvancedTools] = useState(false);
  const [structuredDraft, setStructuredDraft] = useState<WorkshopStructuredDraftState>(() =>
    createEmptyStructuredDraft('planning'),
  );
  const [pendingDraftPatch, setPendingDraftPatch] = useState<WorkshopDraftPatchProposal | null>(null);

  const [diagnosisReport, setDiagnosisReport] = useState<Record<string, unknown> | null>(null);
  const [showDiagnosis, setShowDiagnosis] = useState(false);
  const [isRendering, setIsRendering] = useState(false);
  const [guidedSubject, setGuidedSubject] = useState<string | null>(null);
  const [guidedSuggestions, setGuidedSuggestions] = useState<GuidedTopicSuggestion[]>([]);
  const [guidedPhase, setGuidedPhase] = useState<GuidedConversationPhase>('subject_input');
  const [guidedPageRanges, setGuidedPageRanges] = useState<GuidedTopicSelectionResponse['recommended_page_ranges']>([]);
  const [guidedStructureOptions, setGuidedStructureOptions] = useState<GuidedStructureOption[]>([]);
  const [guidedNextActionOptions, setGuidedNextActionOptions] = useState<GuidedChoiceOption[]>([]);
  const [isGuidedTopicSelected, setIsGuidedTopicSelected] = useState(false);
  const [isSelectingGuidedTopicId, setIsSelectingGuidedTopicId] = useState<string | null>(null);
  const [isGuidedActionLoading, setIsGuidedActionLoading] = useState(false);
  const [chatMeta, setChatMeta] = useState<StreamMetaPayload | null>(null);
  const [mobileView, setMobileView] = useState<'chat' | 'draft'>('chat');
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const questStart = useMemo(() => readQuestStart(), []);
  const initialMajor = useMemo(
    () => ((location.state as { major?: string } | null)?.major || '誘몄젙'),
    [location.state],
  );
  const isProjectBacked = Boolean(projectId && projectId !== 'demo');
  const guidedProjectId = isProjectBacked ? projectId ?? null : null;
  const fileName = useMemo(() => `${(questStart?.title || 'draft').replace(/\s+/g, '_')}.hwpx`, [questStart]);

  const initWorkshop = useCallback(async () => {
    setIsSessionLoading(true);
    setGuidedSubject(null);
    setGuidedSuggestions([]);
    setGuidedPhase('subject_input');
    setGuidedPageRanges([]);
    setGuidedStructureOptions([]);
    setGuidedNextActionOptions([]);
    setIsGuidedTopicSelected(false);
    setIsSelectingGuidedTopicId(null);
    setIsGuidedActionLoading(false);
    setChatMeta(null);
    setLatestDraftUpdatedAt(null);
    setIsDraftOutOfSync(false);
    setPendingDraftPatch(null);
    setShowDraftControls(false);
    setShowAdvancedTools(false);
    setWorkshopMode('planning');
    setStructuredDraft(createEmptyStructuredDraft('planning'));
    try {
      const sessions = await api.get<WorkshopSessionResponse[]>(`/api/v1/workshops?project_id=${projectId}`);
      const active = sessions.find(session => session.status !== 'completed');
      const preferredQuality = localStorage.getItem('uni_foli_quality_level');
      const createQuality: QualityLevel =
        preferredQuality === 'low' || preferredQuality === 'mid' || preferredQuality === 'high'
          ? preferredQuality
          : 'mid';
      const state = active
        ? await api.get<WorkshopStateResponse>(`/api/v1/workshops/${active.id}`)
        : await api.post<WorkshopStateResponse>('/api/v1/workshops', { project_id: projectId, quality_level: createQuality });

      setWorkshopState(state);
      setQualityLevel(state.session.quality_level);

      if (state.latest_artifact) {
        setRenderArtifact(state.latest_artifact);
        const fromArtifact =
          normalizeStructuredDraft(
            state.latest_artifact.structured_draft ||
              state.latest_artifact.evidence_map?.coauthoring?.structured_draft,
          ) ||
          markdownToStructuredDraft(String(state.latest_artifact.report_markdown || ''), 'planning');
        setStructuredDraft(fromArtifact);
        setWorkshopMode(fromArtifact.mode);
        setDocumentContent(structuredDraftToMarkdown(fromArtifact));
        setLatestDraftUpdatedAt(state.latest_artifact.updated_at ?? null);
        setIsDraftOutOfSync(false);
      }

      const turns = state.session.turns || [];
      const loadedMessages: Message[] = [];
      turns.forEach(turn => {
        const role: MessageRole = (turn.speaker_role === 'assistant' || turn.speaker_role === 'bot') ? 'foli' : 'user';
        const content = (role === 'foli' ? (turn.response || turn.query) : turn.query) || '';
        const draftPatch = normalizeStructuredDraftPatch(turn.action_payload?.draft_patch);
        
        if (role === 'foli') {
          loadedMessages.push({ id: turn.id, role: 'foli', content, draftPatch: draftPatch || undefined });
        } else {
          loadedMessages.push({ id: turn.id, role: 'user', content });
          if (turn.response) {
            loadedMessages.push({ id: `${turn.id}-A`, role: 'foli', content: turn.response });
          }
        }
      });

      if (loadedMessages.length) {
        setMessages(loadedMessages);
        setGuidedPhase('freeform_coauthoring');
        setIsGuidedTopicSelected(true);
      } else {
        try {
          const guidedStart = await api.post<GuidedChatStartResponse>('/api/v1/guided-chat/start', {
            project_id: projectId,
          });
          const greeting = ((guidedStart?.greeting || GUIDED_CHAT_GREETING) ?? '').trim();
          const stateSummary = guidedStart.state_summary || {};
          const resolvedPhase = guidedStart.phase || inferGuidedPhase(stateSummary);
          const greetingMessage = formatAssistantMessageWithEvidenceNote(
            guidedStart.assistant_message || greeting,
            guidedStart.evidence_gap_note,
          );

          const cachedStarter =
            typeof stateSummary.starter_draft_markdown === 'string' && stateSummary.starter_draft_markdown.trim()
              ? stateSummary.starter_draft_markdown
              : null;
          const cachedSubject =
            typeof stateSummary.subject === 'string' && stateSummary.subject.trim()
              ? stateSummary.subject
              : null;
          const cachedSuggestions = Array.isArray(stateSummary.suggestions)
            ? normalizeGuidedSuggestions({
                greeting,
                subject: cachedSubject || '탐구',
                suggestions: stateSummary.suggestions as GuidedTopicSuggestion[],
                evidence_gap_note: guidedStart.evidence_gap_note,
              })
            : [];
          const cachedPageRanges = Array.isArray(stateSummary.recommended_page_ranges)
            ? (stateSummary.recommended_page_ranges as GuidedTopicSelectionResponse['recommended_page_ranges'])
            : [];
          const cachedStructureOptions = Array.isArray(stateSummary.structure_options)
            ? (stateSummary.structure_options as GuidedStructureOption[])
            : [];
          const cachedNextActionOptions = Array.isArray(stateSummary.next_action_options)
            ? (stateSummary.next_action_options as GuidedChoiceOption[])
            : [];

          const restoredChoiceGroups =
            guidedStart.choice_groups && guidedStart.choice_groups.length > 0
              ? guidedStart.choice_groups
              : resolvedPhase === 'specific_topic_check'
                ? [buildSpecificTopicCheckGroup()]
                : resolvedPhase === 'subject_input'
                  ? [buildSubjectQuickPickGroup()]
                  : resolvedPhase === 'topic_selection' && cachedSuggestions.length > 0
                    ? [buildTopicChoiceGroup(cachedSuggestions)]
                    : resolvedPhase === 'page_range_selection' && cachedPageRanges.length > 0
                      ? [buildPageRangeChoiceGroup(cachedPageRanges)]
                      : resolvedPhase === 'structure_selection' && cachedStructureOptions.length > 0
                        ? [buildStructureChoiceGroup(cachedStructureOptions)]
                        : resolvedPhase === 'drafting_next_step' && cachedNextActionOptions.length > 0
                          ? [buildNextActionChoiceGroup(cachedNextActionOptions)]
                          : [];

          if (guidedStart.limited_mode) {
            setChatMeta({
              profile: 'standard',
              limited_mode: true,
              limited_reason: guidedStart.limited_reason || 'limited_context',
            });
          }

          setGuidedPhase(resolvedPhase);
          setIsGuidedTopicSelected(isGuidedSetupComplete(resolvedPhase));
          setGuidedSubject(cachedSubject);
          setGuidedSuggestions(cachedSuggestions);
          setGuidedPageRanges(cachedPageRanges);
          setGuidedStructureOptions(cachedStructureOptions);
          setGuidedNextActionOptions(cachedNextActionOptions);

          if (cachedStarter && !state.latest_artifact) {
            const derived = markdownToStructuredDraft(cachedStarter, 'planning');
            setStructuredDraft(derived);
            setWorkshopMode(derived.mode);
            setDocumentContent(structuredDraftToMarkdown(derived));
          }

          setMessages([
            {
              id: 'init',
              role: 'foli',
              content: greetingMessage,
              phase: resolvedPhase,
              topicSubject: cachedSubject || undefined,
              topicSuggestions: resolvedPhase === 'topic_selection' ? cachedSuggestions : undefined,
              pageRangeOptions: resolvedPhase === 'page_range_selection' ? cachedPageRanges : undefined,
              structureOptions:
                resolvedPhase === 'structure_selection' || resolvedPhase === 'drafting_next_step'
                  ? cachedStructureOptions
                  : undefined,
              nextActionOptions: resolvedPhase === 'drafting_next_step' ? cachedNextActionOptions : undefined,
              choiceGroups: restoredChoiceGroups,
            },
          ]);
        } catch {
          setMessages([
            {
              id: 'init',
              role: 'foli',
              content: GUIDED_CHAT_GREETING,
              phase: 'subject_input',
              choiceGroups: [buildSubjectQuickPickGroup()],
            },
          ]);
        }
      }
      api.get<{ result_payload?: Record<string, unknown> }>(`/api/v1/diagnosis/project/${projectId}/latest`)
        .then(res => {
          if (res?.result_payload) {
            setDiagnosisReport(res.result_payload);
            setShowDiagnosis(true);
          }
        })
        .catch(() => {});
    } catch (error) {
      console.error('Workshop init failed:', error);
      toast.error('?뚰겕?띿쓣 遺덈윭?ㅼ? 紐삵뻽?듬땲?? 濡쒖뺄 紐⑤뱶濡??꾪솚?⑸땲??');
      setGuidedPhase('freeform_coauthoring');
      setIsGuidedTopicSelected(true);
      setMessages([{ id: 'fallback', role: 'foli', content: '?몄뀡 ?곌껐???ㅽ뙣?덉뒿?덈떎. 濡쒖뺄?먯꽌 珥덉븞 ?묒꽦??吏꾪뻾?섏떎 ???덉뒿?덈떎.' }]);
    } finally {
      setIsSessionLoading(false);
    }
  }, [projectId]);

  useEffect(() => {
    const savedLevel = localStorage.getItem('uni_foli_quality_level');
    if (savedLevel === 'low' || savedLevel === 'mid' || savedLevel === 'high') {
      setQualityLevel(savedLevel as QualityLevel);
    }
    if (!documentContent) {
      const seed =
        questStart?.document_seed_markdown ||
        `# [?곌뎄 珥덉븞] ${questStart?.title || '??二쇱젣'}\n\n## 諛곌꼍 諛?臾몄젣?섏떇\n\n## ?듭떖 ?먭뎄 ?댁슜 1\n\n## ?듭떖 ?먭뎄 ?댁슜 2\n\n## ?듭떖 ?먭뎄 ?댁슜 3\n\n## 寃곕줎 諛??ㅼ쓬 ?④퀎`;
      const derived = markdownToStructuredDraft(seed, 'planning');
      setStructuredDraft(derived);
      setWorkshopMode(derived.mode);
      setDocumentContent(structuredDraftToMarkdown(derived));
    }

    if (isProjectBacked) {
      void initWorkshop();
    } else {
      setIsSessionLoading(false);
      setGuidedPhase('freeform_coauthoring');
      setIsGuidedTopicSelected(true);
      setMessages([{ id: 'demo-init', role: 'foli', content: '?곕え 紐⑤뱶?낅땲?? ?좊땲?대━?먭쾶 吏덈Ц?섎㈃ 珥덉븞 ?묒꽦???꾩??쒕┰?덈떎.' }]);
    }
  }, [initialMajor, isProjectBacked, initWorkshop, questStart, documentContent]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const saveDraftWithSync = useCallback(
    async (content: string, expectedUpdatedAt: string | null, retryOnConflict = true) => {
      if (!workshopState?.session.id) return;

      const attemptSave = async (
        nextContent: string,
        nextExpectedUpdatedAt: string | null,
        canRetry: boolean,
      ): Promise<void> => {
        try {
          const saved = await api.put<WorkshopSaveDraftResponse>(
            `/api/v1/workshops/${workshopState.session.id}/drafts/latest`,
            {
              document_content: nextContent,
              expected_updated_at: nextExpectedUpdatedAt ?? undefined,
              mode: workshopMode,
              structured_draft: structuredDraft,
            },
          );
          setLatestDraftUpdatedAt(saved.saved_updated_at);
          if (saved.structured_draft) {
            const normalized = normalizeStructuredDraft(saved.structured_draft, workshopMode);
            if (normalized) {
              setStructuredDraft(normalized);
              setWorkshopMode(normalized.mode);
            }
          }
          setIsDraftOutOfSync(false);
          return;
        } catch (error: any) {
          const conflictDetail = error?.response?.status === 409 ? error?.response?.data?.detail : null;
          if (
            canRetry &&
            conflictDetail &&
            typeof conflictDetail === 'object' &&
            typeof conflictDetail.latest_document_content === 'string' &&
            typeof conflictDetail.latest_updated_at === 'string'
          ) {
            const remoteContent = String(conflictDetail.latest_document_content || '');
            const remoteUpdatedAt = String(conflictDetail.latest_updated_at || '');
            const remoteStructured = normalizeStructuredDraft(
              conflictDetail.latest_structured_draft,
              workshopMode,
            );
            const mergedContent =
              remoteContent.trim() === nextContent.trim() || remoteContent.includes(nextContent.trim())
                ? remoteContent
                : `${remoteContent}\n\n${nextContent}`;

            setDocumentContent(mergedContent);
            if (remoteStructured) {
              setStructuredDraft(remoteStructured);
              setWorkshopMode(remoteStructured.mode);
            } else {
              const mergedStructured = markdownToStructuredDraft(mergedContent, workshopMode);
              setStructuredDraft(mergedStructured);
            }
            setLatestDraftUpdatedAt(remoteUpdatedAt);
            setIsDraftOutOfSync(true);
            toast('?ㅻⅨ ??뿉??珥덉븞??蹂寃쎈릺??理쒖떊 ?댁슜 蹂묓빀 ???ㅼ떆 ??ν뻽?듬땲??');
            await attemptSave(mergedContent, remoteUpdatedAt, false);
            return;
          }
          console.error('Autosave failed:', error);
        }
      };

      await attemptSave(content, expectedUpdatedAt, retryOnConflict);
    },
    [workshopState?.session.id, structuredDraft, workshopMode],
  );

  useEffect(() => {
    if (!workshopState?.session.id || !documentContent) return;
    const timeout = setTimeout(() => {
      void saveDraftWithSync(documentContent, latestDraftUpdatedAt);
    }, 3000);
    return () => clearTimeout(timeout);
  }, [documentContent, latestDraftUpdatedAt, saveDraftWithSync, workshopState?.session.id]);

  useEffect(() => {
    const nextMarkdown = structuredDraftToMarkdown(structuredDraft);
    if (nextMarkdown !== documentContent) {
      setDocumentContent(nextMarkdown);
    }
  }, [structuredDraft, documentContent]);


  const pushGuidedAssistantMessage = useCallback((nextMessage: Omit<Message, 'id' | 'role'> & { content: string }) => {
    setMessages((prev) => [
      ...prev,
      {
        id: crypto.randomUUID(),
        role: 'foli',
        ...nextMessage,
      },
    ]);
  }, []);

  const handleGuidedTopicSelection = useCallback(
    async (
      topicId: string,
      subjectFromMessage?: string,
      suggestionsOverride?: GuidedTopicSuggestion[],
    ) => {
      const currentSuggestions = suggestionsOverride?.length ? suggestionsOverride : guidedSuggestions;
      if (!currentSuggestions.length || !guidedProjectId) return;

      setIsGuidedActionLoading(true);
      setIsSelectingGuidedTopicId(topicId);
      try {
        const response = await api.post<GuidedTopicSelectionResponse>('/api/v1/guided-chat/topic-selection', {
          project_id: guidedProjectId,
          selected_topic_id: topicId,
          subject: subjectFromMessage || guidedSubject || undefined,
          suggestions: currentSuggestions,
        });
        if (response.limited_mode) {
          setChatMeta({
            profile: 'fast',
            limited_mode: true,
            limited_reason: response.limited_reason || 'limited_context',
          });
        }

        const derived = markdownToStructuredDraft(response.starter_draft_markdown, 'outline');
        setStructuredDraft(derived);
        setWorkshopMode(derived.mode);
        setDocumentContent(structuredDraftToMarkdown(derived));
        setLatestDraftUpdatedAt(null);
        setIsDraftOutOfSync(false);

        const nextPhase = response.phase || 'page_range_selection';
        const pageRanges = response.recommended_page_ranges || [];
        const structureOptions = response.structure_options || [];
        const nextActions = response.next_action_options || [];

        setGuidedPhase(nextPhase);
        setIsGuidedTopicSelected(false);
        setGuidedSuggestions(currentSuggestions);
        setGuidedPageRanges(pageRanges);
        setGuidedStructureOptions(structureOptions);
        setGuidedNextActionOptions(nextActions);

        pushGuidedAssistantMessage({
          content: [response.assistant_message || '', formatGuidedSelectionMessage(response)].filter(Boolean).join('\n\n'),
          phase: nextPhase,
          pageRangeOptions: pageRanges,
          structureOptions,
          nextActionOptions: nextActions,
          choiceGroups:
            response.choice_groups && response.choice_groups.length > 0
              ? response.choice_groups
              : [buildPageRangeChoiceGroup(pageRanges)],
        });
        toast.success('주제 선택이 반영되었어요. 이제 분량을 정해볼게요.');
      } catch (error) {
        console.error('Guided topic selection failed:', error);
        toast.error('주제 선택을 반영하지 못했습니다. 다시 시도해 주세요.');
      } finally {
        setIsSelectingGuidedTopicId(null);
        setIsGuidedActionLoading(false);
      }
    },
    [guidedProjectId, guidedSubject, guidedSuggestions, pushGuidedAssistantMessage],
  );

  const handleGuidedPageRangeSelection = useCallback(
    async (selectedPageRangeLabel: string) => {
      if (!guidedProjectId) return;

      setIsGuidedActionLoading(true);
      try {
        const response = await api.post<GuidedPageRangeSelectionResponse>('/api/v1/guided-chat/page-range-selection', {
          project_id: guidedProjectId,
          selected_page_range_label: selectedPageRangeLabel,
        });

        if (response.limited_mode) {
          setChatMeta({
            profile: 'fast',
            limited_mode: true,
            limited_reason: response.limited_reason || 'limited_context',
          });
        }

        const nextPhase = response.phase || 'structure_selection';
        const nextStructureOptions = response.structure_options || guidedStructureOptions;

        setGuidedPhase(nextPhase);
        setIsGuidedTopicSelected(false);
        setGuidedStructureOptions(nextStructureOptions);

        pushGuidedAssistantMessage({
          content: formatGuidedPageRangeMessage(response),
          phase: nextPhase,
          structureOptions: nextStructureOptions,
          choiceGroups:
            response.choice_groups && response.choice_groups.length > 0
              ? response.choice_groups
              : [buildStructureChoiceGroup(nextStructureOptions)],
        });
      } catch (error) {
        console.error('Guided page-range selection failed:', error);
        toast.error('분량 선택을 반영하지 못했습니다. 다시 시도해 주세요.');
      } finally {
        setIsGuidedActionLoading(false);
      }
    },
    [guidedProjectId, guidedStructureOptions, pushGuidedAssistantMessage],
  );

  const handleGuidedStructureSelection = useCallback(
    async (selectedStructureId: string) => {
      if (!guidedProjectId) return;

      setIsGuidedActionLoading(true);
      try {
        const response = await api.post<GuidedStructureSelectionResponse>('/api/v1/guided-chat/structure-selection', {
          project_id: guidedProjectId,
          selected_structure_id: selectedStructureId,
        });

        if (response.limited_mode) {
          setChatMeta({
            profile: 'fast',
            limited_mode: true,
            limited_reason: response.limited_reason || 'limited_context',
          });
        }

        const nextPhase = response.phase || 'drafting_next_step';
        const nextActions = response.next_action_options || [];

        setGuidedPhase(nextPhase);
        setGuidedNextActionOptions(nextActions);
        setIsGuidedTopicSelected(true);

        pushGuidedAssistantMessage({
          content: formatGuidedStructureMessage(response),
          phase: nextPhase,
          nextActionOptions: nextActions,
          choiceGroups:
            response.choice_groups && response.choice_groups.length > 0
              ? response.choice_groups
              : [buildNextActionChoiceGroup(nextActions)],
        });
      } catch (error) {
        console.error('Guided structure selection failed:', error);
        toast.error('구성 선택을 반영하지 못했습니다. 다시 시도해 주세요.');
      } finally {
        setIsGuidedActionLoading(false);
      }
    },
    [guidedProjectId, pushGuidedAssistantMessage],
  );

  const requestGuidedSuggestions = useCallback(
    async (subjectText: string) => {
      if (!guidedProjectId) return;
      const pendingId = crypto.randomUUID();
      setIsGuidedActionLoading(true);
      setMessages((prev) => [
        ...prev,
        {
          id: pendingId,
          role: 'foli',
          content: '학생 기록을 바탕으로 주제 3가지를 정리하고 있어요. 잠시만 기다려주세요.',
        },
      ]);
      try {
        const response = await api.post<GuidedTopicSuggestionResponse>('/api/v1/guided-chat/topic-suggestions', {
          project_id: guidedProjectId,
          subject: subjectText,
        });
        const normalizedSuggestions = normalizeGuidedSuggestions(response);
        if (response.limited_mode) {
          setChatMeta({
            profile: 'fast',
            limited_mode: true,
            limited_reason: response.limited_reason || 'limited_context',
          });
        }

        const nextPhase = response.phase || 'topic_selection';
        const choiceGroups =
          response.choice_groups && response.choice_groups.length > 0
            ? response.choice_groups
            : [buildTopicChoiceGroup(normalizedSuggestions)];

        setGuidedPhase(nextPhase);
        setIsGuidedTopicSelected(false);
        setGuidedSubject(response.subject);
        setGuidedSuggestions(normalizedSuggestions);
        setGuidedPageRanges([]);
        setGuidedStructureOptions([]);
        setGuidedNextActionOptions([]);

        setMessages((prev) =>
          prev.map((message) =>
            message.id === pendingId
              ? {
                  ...message,
                  content: [response.assistant_message || '', formatGuidedSuggestionMessage(response)]
                    .filter(Boolean)
                    .join('\n\n'),
                  phase: nextPhase,
                  topicSubject: response.subject,
                  topicSuggestions: normalizedSuggestions,
                  choiceGroups,
                }
              : message,
          ),
        );
      } catch (error) {
        setMessages((prev) => prev.filter((message) => message.id !== pendingId));
        throw error;
      } finally {
        setIsGuidedActionLoading(false);
      }
    },
    [guidedProjectId],
  );
  const handleOpenProfessionalEditor = useCallback(() => {
    navigate(`/app/editor/${projectId || 'demo'}`, {
      state: {
        seedMarkdown: documentContent,
      },
    });
  }, [documentContent, navigate, projectId]);

  const coauthoringTier = useMemo<'basic' | 'plus' | 'pro'>(() => {
    if (qualityLevel === 'high') return 'pro';
    if (qualityLevel === 'mid') return 'plus';
    return 'basic';
  }, [qualityLevel]);

  const applyPatchToDraft = useCallback(
    (patch: WorkshopDraftPatchProposal, approved: boolean, allowOverwriteStudentContent = false) => {
      let applied = false;
      let blockedReason: string | undefined;
      setStructuredDraft((prev) => {
        const result = applyDraftPatch(prev, patch, {
          approved,
          allowOverwriteStudentContent,
        });
        applied = result.applied;
        blockedReason = result.blockedReason;
        if (result.applied) {
          setWorkshopMode(result.next.mode);
        }
        return result.next;
      });
      if (applied) {
        setPendingDraftPatch(null);
        if (approved) {
          toast.success('?뱀씤???뱀뀡 ?쒖븞???곗륫 援ъ“ 珥덉븞??諛섏쁺?덉뒿?덈떎.');
        }
      } else if (blockedReason === 'student_content_protected') {
        toast('학생이 직접 작성한 섹션은 자동 덮어쓰기를 막고 있어요. 내용을 확인한 뒤 수동으로 반영해 주세요.');
      }
      return applied;
    },
    [],
  );

  const updateDraftBlock = useCallback((blockId: string, nextContent: string) => {
    setStructuredDraft((prev) => ({
      ...prev,
      blocks: prev.blocks.map((block) =>
        block.block_id === blockId
          ? {
              ...block,
              content_markdown: nextContent,
              attribution: 'student-authored',
              updated_at: new Date().toISOString(),
            }
          : block,
      ),
    }));
  }, []);

  const updateDraftHeading = useCallback((blockId: string, nextHeading: string) => {
    setStructuredDraft((prev) => ({
      ...prev,
      blocks: prev.blocks.map((block) =>
        block.block_id === blockId
          ? {
              ...block,
              heading: nextHeading || block.heading,
              attribution: block.attribution,
              updated_at: new Date().toISOString(),
            }
          : block,
      ),
    }));
  }, []);

  const handleSend = async (overriddenText?: string) => {
    const text = (overriddenText ?? input ?? '').trim();
    if (!text || isTyping || isSelectingGuidedTopicId || isGuidedActionLoading) return;
    if (!overriddenText) setInput('');

    if (pendingDraftPatch && isPatchAcceptanceMessage(text)) {
      applyPatchToDraft(pendingDraftPatch, true, false);
    }

    setMessages(prev => [...prev, { id: crypto.randomUUID(), role: 'user', content: text }]);

    if (isProjectBacked && !isGuidedSetupComplete(guidedPhase)) {
      setIsTyping(true);
      try {
        if (guidedPhase === 'subject_input') {
          const normalizedSubject = text.trim();
          const broadSubject = looksLikeBroadSubject(normalizedSubject);
          setGuidedSubject(normalizedSubject);
          setGuidedPhase('specific_topic_check');
          pushGuidedAssistantMessage({
            content: broadSubject
              ? `좋아요. ${normalizedSubject}로 진행해볼게요.\n특별히 생각해 둔 주제가 있을까요? 아직 없다면 학생 기록 기반으로 3개 추천해드릴게요.`
              : `좋아요. ${normalizedSubject} 방향으로 진행해볼게요.\n이미 생각해둔 탐구 질문이 있다면 알려주세요. 없으면 학생 기록을 바탕으로 3개 추천해드릴게요.`,
            phase: 'specific_topic_check',
            topicSubject: normalizedSubject,
            choiceGroups: [buildSpecificTopicCheckGroup()],
          });
          return;
        }

        if (guidedPhase === 'specific_topic_check') {
          if (isRecommendationAffirmative(text)) {
            await requestGuidedSuggestions(guidedSubject || text);
            return;
          }
          if (isSpecificTopicAffirmative(text)) {
            pushGuidedAssistantMessage({
              content: '좋아요. 생각해둔 주제를 한 문장으로 적어주시면, 그 방향까지 반영해서 주제 3가지를 제안할게요.',
              phase: 'specific_topic_check',
              topicSubject: guidedSubject || undefined,
              choiceGroups: [buildSpecificTopicCheckGroup()],
            });
            return;
          }
          await requestGuidedSuggestions(text);
          return;
        }

        if (guidedPhase === 'topic_selection' || guidedPhase === 'topic_recommendation') {
          const selectedFromText = resolveGuidedSelectionFromText(text, guidedSuggestions);
          if (selectedFromText) {
            await handleGuidedTopicSelection(selectedFromText.id, guidedSubject || undefined);
          } else {
            pushGuidedAssistantMessage({
              content: '주제 카드를 눌러 선택하면 바로 분량/구성 단계로 이어갈게요.',
              phase: 'topic_selection',
              topicSubject: guidedSubject || undefined,
              topicSuggestions: guidedSuggestions,
              choiceGroups: [buildTopicChoiceGroup(guidedSuggestions)],
            });
          }
          return;
        }

        if (guidedPhase === 'page_range_selection') {
          const selectedPageLabel = resolvePageRangeLabel(text, guidedPageRanges);
          if (selectedPageLabel) {
            await handleGuidedPageRangeSelection(selectedPageLabel);
          } else {
            pushGuidedAssistantMessage({
              content: '분량 카드를 눌러 선택해 주세요. 선택 후 바로 구성 스타일을 물어볼게요.',
              phase: 'page_range_selection',
              pageRangeOptions: guidedPageRanges,
              choiceGroups: [buildPageRangeChoiceGroup(guidedPageRanges)],
            });
          }
          return;
        }

        if (guidedPhase === 'structure_selection') {
          const selectedStructureId = resolveStructureOptionId(text, guidedStructureOptions);
          if (selectedStructureId) {
            await handleGuidedStructureSelection(selectedStructureId);
          } else {
            pushGuidedAssistantMessage({
              content: '구성 스타일 카드를 눌러 선택해 주세요.',
              phase: 'structure_selection',
              structureOptions: guidedStructureOptions,
              choiceGroups: [buildStructureChoiceGroup(guidedStructureOptions)],
            });
          }
          return;
        }
      } catch (error) {
        console.error('Guided setup flow failed:', error);
        toast.error('가이드 설정 중 오류가 발생했습니다. 다시 시도해 주세요.');
      } finally {
        setIsTyping(false);
      }
      return;
    }

    if (isProjectBacked && guidedPhase === 'drafting_next_step') {
      setGuidedPhase('freeform_coauthoring');
      setIsGuidedTopicSelected(true);
    }

    setIsTyping(true);
    setChatMeta(null);

    const foliId = crypto.randomUUID();
    setMessages(prev => [...prev, { id: foliId, role: 'foli', content: '' }]);

    let accumulated = '';
    let pendingDelta = '';
    let streamedPatch: WorkshopDraftPatchProposal | null = null;
    let streamAuthSource: AuthTokenSource | null = null;
    let streamLimitedReason: string | null = null;
    let flushTimer: number | null = null;

    const flushBufferedDelta = () => {
      if (!pendingDelta) {
        flushTimer = null;
        return;
      }
      accumulated += pendingDelta;
      pendingDelta = '';
      flushTimer = null;
      setMessages(prev => prev.map(message => (message.id === foliId ? { ...message, content: accumulated } : message)));
    };

    try {
      const streamResult = await streamFoliReply(
        isProjectBacked ? projectId : undefined,
        workshopState?.session.id,
        text,
        documentContent,
        workshopMode,
        structuredDraft,
        delta => {
          pendingDelta += delta;
          if (flushTimer === null) {
            flushTimer = window.setTimeout(flushBufferedDelta, 40);
          }
        },
        meta => {
          setChatMeta(meta);
          if (meta.limited_mode) {
            streamLimitedReason = String(meta.limited_reason || 'limited_context');
          }
          if (
            meta.coauthoring_mode === 'planning' ||
            meta.coauthoring_mode === 'outline' ||
            meta.coauthoring_mode === 'section_drafting' ||
            meta.coauthoring_mode === 'revision'
          ) {
            setWorkshopMode(meta.coauthoring_mode);
            setStructuredDraft((prev) => ({ ...prev, mode: meta.coauthoring_mode as WorkshopMode }));
          }
        },
        patch => {
          const normalizedPatch = normalizeStructuredDraftPatch(patch);
          if (normalizedPatch) {
            streamedPatch = normalizedPatch;
            setPendingDraftPatch(normalizedPatch);
          }
        },
      );
      streamAuthSource = streamResult.authSource;
      const raw = streamResult.text;

      if (flushTimer !== null) {
        window.clearTimeout(flushTimer);
        flushTimer = null;
      }
      flushBufferedDelta();

      if (streamLimitedReason) {
        console.warn('Workshop chat stream returned limited_mode fallback.', {
          reason: streamLimitedReason,
          auth_source: streamAuthSource,
          project_id: projectId ?? null,
          workshop_id: workshopState?.session.id ?? null,
        });
        if (streamLimitedReason === 'llm_unavailable') {
          toast.error('AI 紐⑤뜽 ?곌껐??遺덉븞?뺥븯???쒗븳 紐⑤뱶 ?덈궡濡??꾪솚?섏뿀?댁슂.');
        }
      }

      const extracted = extractPatchTagFromRaw(raw);
      const resolvedPatch = streamedPatch || extracted.patch;
      const responseContent = extracted.cleaned || raw || accumulated || '?묐떟???앹꽦?섏? 紐삵뻽?듬땲??';
      const shouldAutoApplyPatch =
        resolvedPatch !== null &&
        coauthoringTier !== 'basic' &&
        (isPatchAcceptanceMessage(text) || isSectionDraftIntent(text));

      if (resolvedPatch && shouldAutoApplyPatch) {
        const autoApplied = applyPatchToDraft(resolvedPatch, true, false);
        if (!autoApplied) {
          setPendingDraftPatch(resolvedPatch);
        }
      }

      setMessages(prev =>
        prev.map(message =>
          message.id === foliId
            ? {
                ...message,
                content: responseContent,
                draftPatch: resolvedPatch && !shouldAutoApplyPatch ? resolvedPatch : undefined,
              }
            : message,
        ),
      );
    } catch (error) {
      if (flushTimer !== null) {
        window.clearTimeout(flushTimer);
        flushTimer = null;
      }
      flushBufferedDelta();

      let fallbackContent = buildFoliFallback(text);
      if (error instanceof ChatStreamError) {
        console.error('Workshop chat stream failed with classified transport error.', {
          code: error.code,
          endpoint: error.endpoint,
          status: error.status,
          content_type: error.contentType,
          detail: error.detail,
          auth_source: error.authSource ?? streamAuthSource,
          project_id: projectId ?? null,
          workshop_id: workshopState?.session.id ?? null,
        });
        toast.error(resolveChatStreamToastMessage(error));
        const hint = resolveChatStreamFallbackHint(error);
        if (hint) {
          fallbackContent = `${fallbackContent}\n\n李멸퀬: ${hint}`;
        }
      } else {
        console.error('AI reply stream failed with unexpected error:', error);
        toast.error('梨꾪똿 ?묐떟 ?앹꽦???ㅽ뙣?덉뒿?덈떎. ?좎떆 ???ㅼ떆 ?쒕룄??二쇱꽭??');
      }
      setMessages(prev =>
        prev.map(message =>
          message.id === foliId
            ? {
                ...message,
                content: fallbackContent,
              }
            : message,
        ),
      );
    } finally {
      setIsTyping(false);
    }
  };

  const handleGuidedChoiceSelect = useCallback(
    async (groupId: string, option: GuidedChoiceOption, sourceMessage: Message) => {
      const rawValue = String(option.value || option.label || option.id || '').trim();
      if (!rawValue) return;

      if (groupId === 'next-action-selection') {
        setGuidedPhase('freeform_coauthoring');
        setIsGuidedTopicSelected(true);
        await handleSend(rawValue);
        return;
      }

      setMessages((prev) => [...prev, { id: crypto.randomUUID(), role: 'user', content: option.label || rawValue }]);

      if (groupId === 'subject-quick-picks') {
        setGuidedSubject(rawValue);
        setGuidedPhase('specific_topic_check');
        pushGuidedAssistantMessage({
          content: `좋아요. ${rawValue}로 진행해볼게요.\n특별히 생각해 둔 주제가 있을까요? 아직 없다면 학생 기록 기반으로 3개 추천해드릴게요.`,
          phase: 'specific_topic_check',
          topicSubject: rawValue,
          choiceGroups: [buildSpecificTopicCheckGroup()],
        });
        return;
      }

      if (groupId === 'specific-topic-check') {
        if (option.id.includes('no')) {
          try {
            await requestGuidedSuggestions(guidedSubject || rawValue);
          } catch (error) {
            console.error('Guided suggestion failed from choice:', error);
            toast.error('주제 추천을 불러오지 못했습니다. 다시 시도해 주세요.');
          }
          return;
        }
        pushGuidedAssistantMessage({
          content: '좋아요. 생각해둔 주제를 한 문장으로 적어주시면 그 방향까지 반영해서 3개 주제를 제안할게요.',
          phase: 'specific_topic_check',
          topicSubject: guidedSubject || undefined,
          choiceGroups: [buildSpecificTopicCheckGroup()],
        });
        return;
      }

      if (groupId === 'topic-selection') {
        await handleGuidedTopicSelection(
          rawValue,
          sourceMessage.topicSubject || guidedSubject || undefined,
          sourceMessage.topicSuggestions || guidedSuggestions,
        );
        return;
      }

      if (groupId === 'page-range-selection') {
        await handleGuidedPageRangeSelection(rawValue);
        return;
      }

      if (groupId === 'structure-selection') {
        await handleGuidedStructureSelection(option.id);
        return;
      }
    },
    [
      guidedSubject,
      guidedSuggestions,
      handleSend,
      handleGuidedPageRangeSelection,
      handleGuidedStructureSelection,
      handleGuidedTopicSelection,
      pushGuidedAssistantMessage,
      requestGuidedSuggestions,
    ],
  );

  const handleApplyPatchFromMessage = useCallback(
    (patch: WorkshopDraftPatchProposal) => {
      setPendingDraftPatch(patch);
      applyPatchToDraft(patch, true, false);
    },
    [applyPatchToDraft],
  );

  const handleGenerateDraft = async () => {
    if (!workshopState || isRendering) return;
    setIsRendering(true);
    try {
      await api.post(`/api/v1/workshops/${workshopState.session.id}/render`);
      toast.success('寃곌낵臾??앹꽦???붿껌?덉뒿?덈떎.');
    } catch (error) {
      console.error('Failed to render draft:', error);
      toast.error('?앹꽦 ?붿껌???ㅽ뙣?덉뒿?덈떎.');
    } finally {
      setIsRendering(false);
    }
  };

  const handleSaveDraft = () => {
    saveArchiveItem({
      id: crypto.randomUUID(),
      projectId: projectId ?? null,
      title: fileName.replace('.hwpx', ''),
      subject: initialMajor,
      createdAt: new Date().toISOString(),
      contentMarkdown: documentContent,
    });
    toast.success('?뚰겕??珥덉븞????ν뻽?듬땲??');
    confetti({ particleCount: 80, spread: 62, origin: { y: 0.65 } });
  };

  const handleUpdateVisualStatus = async (visualId: string, status: string) => {
    if (!workshopState?.session.id || !workshopState.latest_artifact?.id) return;
    try {
      const response = await api.patch(
        `/api/v1/workshops/${workshopState.session.id}/artifacts/${workshopState.latest_artifact.id}/visuals/${visualId}`,
        { approval_status: status }
      );
      setWorkshopState(response.data);
      toast.success('?곹깭瑜??낅뜲?댄듃?덉뒿?덈떎.');
    } catch (error) {
      console.error('Failed to update visual status:', error);
      toast.error('?곹깭 ?낅뜲?댄듃 ?ㅽ뙣');
    }
  };

  const handleReplaceVisual = async (visualId: string) => {
    if (!workshopState?.session.id || !workshopState.latest_artifact?.id) return;
    try {
      const response = await api.post(
        `/api/v1/workshops/${workshopState.session.id}/artifacts/${workshopState.latest_artifact.id}/visuals/${visualId}/replace`
      );
      setWorkshopState(response.data);
      toast.success('?덈줈???쒓컖 ?먮즺瑜??앹꽦?덉뒿?덈떎.');
    } catch (error) {
      console.error('Failed to replace visual:', error);
      toast.error('?쒓컖 ?먮즺 ?앹꽦 ?ㅽ뙣');
    }
  };

  const qualityMeta = QUALITY_META_MAP[qualityLevel];
  const diagnosisSummary = (diagnosisReport?.summary ?? {}) as {
    headline?: string;
    risk_level?: string;
    gaps?: unknown[];
  };
  const diagnosisHeadline = diagnosisSummary.headline;
  const diagnosisRisk = diagnosisSummary.risk_level;
  const diagnosisRiskKey = typeof diagnosisRisk === 'string' ? diagnosisRisk.toLowerCase() : '';
  const diagnosisRiskLabel = formatDiagnosisRiskLabel(typeof diagnosisRisk === 'string' ? diagnosisRisk : undefined);
  const diagnosisRiskStatus = diagnosisRiskKey === 'safe' ? 'success' : diagnosisRiskKey === 'danger' ? 'danger' : 'warning';
  const diagnosisGapCount = diagnosisSummary.gaps?.length || 0;
  const limitedReason = chatMeta?.limited_reason || null;
  const limitedModeNotice = useMemo(() => {
    if (!chatMeta?.limited_mode) return null;
    if (limitedReason === 'evidence_gap') {
      return {
        title: '洹쇨굅 蹂댁셿 紐⑤뱶媛 ?쒖꽦?붾릺?덉뒿?덈떎',
        description: '?꾩옱 ?뺤씤 媛?ν븳 ?숈깮 湲곕줉???쒗븳?섏뼱 蹂댁닔?곸씤 ?쒖븞留??쒓났?⑸땲??',
      };
    }
    if (limitedReason === 'llm_unavailable') {
      return {
        title: 'AI model connection is temporarily limited.',
        description: 'Gemini/LLM connectivity is unstable, so the chat switched to a safer limited response.',
      };
    }
    return {
      title: '?쒗븳 紐⑤뱶媛 ?쒖꽦?붾릺?덉뒿?덈떎',
      description: '紐⑤뜽 ?곌껐???쇱떆?곸쑝濡?遺덉븞?뺥븯???대쾲 ?묐떟? ?덉쟾??湲곕낯 ?덈궡濡??꾪솚?섏뿀?듬땲??',
    };
  }, [chatMeta?.limited_mode, limitedReason]);
  const guidedSetupComplete = isGuidedSetupComplete(guidedPhase) || isGuidedTopicSelected;
  const guidedPhaseLabel =
    guidedPhase === 'subject_input'
      ? '과목 선택'
      : guidedPhase === 'specific_topic_check'
        ? '주제 구체화'
        : guidedPhase === 'topic_selection' || guidedPhase === 'topic_recommendation'
          ? '주제 선택'
          : guidedPhase === 'page_range_selection'
            ? '분량 선택'
            : guidedPhase === 'structure_selection'
              ? '구성 선택'
              : guidedSetupComplete
                ? '설정 완료'
                : '가이드 진행';
  const inputPlaceholder =
    isProjectBacked && !guidedSetupComplete
      ? '가이드를 따라 과목/주제/분량/구성을 먼저 정해볼게요.'
      : '메시지를 입력해 주세요...';

  return (
    <div className={cn("mx-auto max-w-[1800px] space-y-4 px-2.5 py-3 transition-all duration-700 sm:space-y-6 sm:px-4 sm:py-6", advancedMode && "rounded-[32px] bg-[#004aad]/5 shadow-[inset_0_0_100px_rgba(0,74,173,0.02)] sm:rounded-[48px]")}>
      <motion.div
        animate={advancedMode ? { y: [0, -2, 0] } : {}}
        transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
      >
        <PageHeader
          eyebrow="워크숍"
          title="유니폴리 초안 작업"
          description="업로드된 기록 근거를 바탕으로 초안을 안정적으로 이어서 작성해보세요."
          actions={
            <div className="flex items-center gap-2">
              <SecondaryButton
                data-testid="workshop-advanced-toggle"
                onClick={() => setAdvancedMode(prev => !prev)}
                aria-label={advancedMode ? '怨좉툒 紐⑤뱶 ?꾧린' : '怨좉툒 紐⑤뱶 耳쒓린'}
              >
                {advancedMode ? <ToggleRight size={16} /> : <ToggleLeft size={16} />}
                {advancedMode ? '怨좉툒 紐⑤뱶' : '湲곕낯 紐⑤뱶'}
              </SecondaryButton>
              <SecondaryButton
                onClick={handleGenerateDraft}
                disabled={!workshopState || isRendering || !workshopState.render_requirements?.can_render}
              >
                {isRendering ? <Loader2 size={16} className="animate-spin" /> : <Presentation size={14} />}
                誘몃━蹂닿린 ?앹꽦
              </SecondaryButton>
            </div>
          }
          evidence={
            <div className="flex flex-wrap items-center gap-2">
              <StatusBadge status={isProjectBacked ? 'success' : 'warning'}>
                {isProjectBacked ? '프로젝트 연결' : '데모 모드'}
              </StatusBadge>
              {isProjectBacked && (
                <StatusBadge status={guidedSetupComplete ? 'success' : 'warning'}>
                  {guidedSetupComplete ? '가이드 설정 완료' : `가이드 진행: ${guidedPhaseLabel}`}
                </StatusBadge>
              )}
              <StatusBadge status={qualityMeta.status}>{qualityMeta.label}</StatusBadge>
            </div>
          }
        />

        <div className="mt-6 lg:hidden">
          <div className="inline-flex w-full items-center gap-1 rounded-2xl border border-slate-200 bg-white p-1 shadow-sm">
            <button
              type="button"
              onClick={() => setMobileView('chat')}
              className={cn(
                'h-10 flex-1 rounded-xl px-3 text-sm font-bold transition-all',
                mobileView === 'chat' ? 'bg-[#004aad] text-white shadow-md' : 'text-slate-600 hover:bg-slate-50',
              )}
            >
              梨꾪똿
            </button>
            <button
              type="button"
              onClick={() => setMobileView('draft')}
              className={cn(
                'h-10 flex-1 rounded-xl px-3 text-sm font-bold transition-all',
                mobileView === 'draft' ? 'bg-[#004aad] text-white shadow-md' : 'text-slate-600 hover:bg-slate-50',
              )}
            >
              臾몄꽌
            </button>
          </div>
        </div>

        <div className="mt-6 grid gap-6 lg:grid-cols-[400px_minmax(0,1fr)] xl:grid-cols-[460px_minmax(0,1fr)]">
          <SectionCard
            title="유니폴리 채팅"
            eyebrow="대화"
            className={cn(
              'flex min-h-0 flex-col h-[calc(100dvh-15rem)] min-h-[520px] max-h-[800px]',
              mobileView !== 'chat' && 'hidden lg:flex'
            )}
            bodyClassName="relative flex min-h-0 flex-1 flex-col overflow-hidden p-0"
          >
            <div className="flex h-full flex-col">
              <div className="flex-1 overflow-y-auto px-4 py-4 space-y-6 scroll-smooth">
                {workshopState?.render_requirements && (
                  <div className="mb-2 border-b border-slate-100 bg-slate-50/30 px-4 py-4">
                    <WorkshopProgress 
                      requirements={workshopState.render_requirements} 
                      qualityInfo={workshopState.quality_level_info}
                    />
                  </div>
                )}

                {diagnosisReport && (
                  <SurfaceCard tone="muted" padding="none" className="mb-4 overflow-hidden border-[#004aad]/10 bg-[#004aad]/5">
                    <button
                      type="button"
                      onClick={() => setShowDiagnosis(prev => !prev)}
                      className="flex w-full items-center justify-between px-4 py-3 text-left text-sm font-bold text-slate-700 hover:bg-[#004aad]/10"
                    >
                      <span className="inline-flex items-center gap-2">
                        <div className="h-1.5 w-1.5 rounded-full bg-[#004aad] shadow-sm shadow-[#004aad]/50" />
                        理쒓렐 ?앷린遺 吏꾨떒 ?뺣낫
                      </span>
                      {showDiagnosis ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                    </button>
                    <AnimatePresence>
                      {showDiagnosis && (
                        <motion.div
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          className="overflow-hidden border-t border-[#004aad]/10 px-4 pb-4"
                        >
                          <SurfaceCard padding="sm" className="mt-3 space-y-2 border-none bg-white/60">
                            <p className="text-sm font-bold text-slate-900">{diagnosisHeadline}</p>
                            <div className="flex flex-wrap items-center gap-2">
                              {diagnosisRisk && <StatusBadge status={diagnosisRiskStatus}>{diagnosisRiskLabel}</StatusBadge>}
                              <StatusBadge status="neutral">蹂댁셿 {diagnosisGapCount}</StatusBadge>
                            </div>
                          </SurfaceCard>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </SurfaceCard>
                )}

                {limitedModeNotice && (
                  <WorkflowNotice
                    tone="warning"
                    title={limitedModeNotice.title}
                    description={limitedModeNotice.description}
                    className="mb-4"
                  />
                )}

                {isProjectBacked && !guidedSetupComplete && (
                  <WorkflowNotice
                    tone="info"
                    title="가이드 설정을 먼저 진행해요"
                    description="과목 → 주제 → 분량 → 구성을 카드로 고르면, 그다음부터는 자유 채팅으로 바로 초안을 함께 작성할 수 있어요."
                    className="mb-4"
                  />
                )}

                {!isSessionLoading ? (
                  <div className="space-y-6 pb-4">
                    {messages.map((message) => (
                      <ChatBubble
                        key={message.id}
                        message={message}
                        onApplyDraftPatch={handleApplyPatchFromMessage}
                        onGuidedChoiceSelect={handleGuidedChoiceSelect}
                        isGuidedActionLoading={isGuidedActionLoading}
                        selectingTopicId={isSelectingGuidedTopicId}
                      />
                    ))}
                    <div ref={messagesEndRef} />
                  </div>
                ) : (
                  <div className="flex h-full items-center justify-center py-20">
                    <Loader2 size={24} className="animate-spin text-[#004aad]" />
                  </div>
                )}
              </div>

              <div className="border-t border-slate-100 bg-white p-4">
                <div className="flex items-center gap-3">
                  <input
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' && !e.shiftKey) {
                        e.preventDefault();
                        void handleSend();
                      }
                    }}
                    placeholder={inputPlaceholder}
                    disabled={isTyping || !!isSelectingGuidedTopicId || isGuidedActionLoading}
                    className="flex-1 h-12 rounded-2xl border-2 border-slate-200 bg-slate-50 px-4 text-[15px] font-medium text-slate-900 outline-none transition-all placeholder:text-slate-400 focus:border-[#004aad] disabled:opacity-50"
                  />
                  <button
                    type="button"
                    onClick={() => void handleSend()}
                    disabled={!input.trim() || isTyping || !!isSelectingGuidedTopicId || isGuidedActionLoading}
                    className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#004aad] text-white shadow-lg shadow-[#004aad]/20 transition-all hover:bg-[#003a8a] disabled:bg-slate-200"
                  >
                    {isTyping ? <Loader2 size={20} className="animate-spin" /> : <Send size={20} />}
                  </button>
                </div>
              </div>
            </div>
          </SectionCard>

          <SectionCard
            title="珥덉븞 臾몄꽌"
            description="?좊땲?대━媛 ?쒖븞???댁슜??諛뷀깢?쇰줈 援ъ꽦??臾몄꽌?낅땲?? ?먯쑀濡?쾶 ?섏젙?섍퀬 蹂닿컯??二쇱꽭??"
            eyebrow="珥덉븞 ?묒꽦"
            className={cn(
              'flex min-h-0 flex-col h-[calc(100dvh-15rem)] min-h-[520px] max-h-[800px]',
              mobileView !== 'draft' && 'hidden lg:flex'
            )}
            bodyClassName="flex min-h-0 flex-1 flex-col overflow-hidden p-0"
            actions={
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  onClick={() => setShowDraftControls(prev => !prev)}
                  className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold text-slate-600 transition-colors hover:bg-slate-50"
                >
                  {showDraftControls ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                  珥덉븞 ?듭뀡
                </button>
                <SecondaryButton size="sm" onClick={handleOpenProfessionalEditor}>
                  <PenSquare size={14} className="mr-1.5" />
                  ?꾨Ц ?몄쭛湲?
                </SecondaryButton>
                <PrimaryButton size="sm" onClick={handleSaveDraft}>
                  <Save size={14} className="mr-1.5" />
                  ???
                </PrimaryButton>
                <SecondaryButton size="sm" onClick={() => {
                  const blob = new Blob([documentContent], { type: 'text/markdown' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a');
                  a.href = url;
                  a.download = fileName.replace('.hwpx', '.md');
                  a.click();
                  URL.revokeObjectURL(url);
                }}>
                  <Download size={14} className="mr-1.5" />
                  留덊겕?ㅼ슫
                </SecondaryButton>
              </div>
            }
          >
            <div className={cn("flex flex-1 flex-col overflow-hidden p-3 sm:p-4", advancedMode && "lg:flex-row gap-4")}>
              {isDraftOutOfSync ? (
                  <WorkflowNotice
                    tone="warning"
                    title="초안 동기화 충돌이 감지되었습니다"
                    description="?쒕쾭 理쒖떊蹂멸낵 ?먮룞 蹂묓빀 ???ㅼ떆 ??ν뻽?듬땲?? 蹂묓빀???댁슜??鍮좊Ⅴ寃??뺤씤??二쇱꽭??"
                    className="mb-3"
                  />
              ) : null}

              {pendingDraftPatch ? (
                <SurfaceCard tone="muted" className="mb-3 border-[#004aad]/10 bg-[#004aad]/5 p-3">
                  <p className="text-xs font-black uppercase tracking-wide text-[#004aad]">섹션 제안 대기</p>
                  <p className="mt-1 text-sm font-bold text-slate-900">
                    {pendingDraftPatch.heading || pendingDraftPatch.block_id}
                  </p>
                  {pendingDraftPatch.rationale ? (
                    <p className="mt-1 text-xs font-medium text-slate-600">{pendingDraftPatch.rationale}</p>
                  ) : null}
                  {pendingDraftPatch.evidence_boundary_note ? (
                    <p className="mt-1 text-xs font-semibold text-amber-700">
                      洹쇨굅 寃쎄퀎: {pendingDraftPatch.evidence_boundary_note}
                    </p>
                  ) : null}
                  <div className="mt-2 flex items-center gap-2">
                    <PrimaryButton size="sm" onClick={() => applyPatchToDraft(pendingDraftPatch, true, false)}>
                      珥덉븞??諛섏쁺
                    </PrimaryButton>
                    <SecondaryButton size="sm" onClick={() => setPendingDraftPatch(null)}>
                      ?쒖븞?쇰줈 ?좎?
                    </SecondaryButton>
                  </div>
                </SurfaceCard>
              ) : null}

              {showDraftControls ? (
                <div className={cn("space-y-3", advancedMode && "lg:w-1/2")}>
                  <div className="grid gap-2 sm:grid-cols-4">
                    {WORKSHOP_MODE_OPTIONS.map((option, idx) => (
                      <button
                        key={option.id}
                        type="button"
                        onClick={() => {
                          setWorkshopMode(option.id);
                          setStructuredDraft((prev) => ({ ...prev, mode: option.id }));
                        }}
                        className={cn(
                          'p-2.5 rounded-xl border transition-all text-xs font-semibold text-left',
                          workshopMode === option.id
                            ? 'border-[#004aad]/20 bg-[#004aad]/5 shadow-sm'
                            : 'border-slate-200 bg-white hover:border-slate-300',
                        )}
                      >
                        <p className="text-xs font-black text-slate-800">{option.label}</p>
                        <p className="mt-0.5 text-[11px] font-medium leading-4 text-slate-500">{option.description}</p>
                      </button>
                    ))}
                  </div>

                  <WorkflowNotice
                    tone={coauthoringTier === 'pro' ? 'success' : coauthoringTier === 'plus' ? 'info' : 'warning'}
                    title={
                      coauthoringTier === 'pro'
                        ? '怨좉툒 怨듬룞?묒꽦'
                        : coauthoringTier === 'plus'
                          ? '?뺤옣 怨듬룞?묒꽦'
                          : '湲곕낯 怨듬룞?묒꽦'
                    }
                    description={
                      coauthoringTier === 'basic'
                        ? 'AI ?쒖븞? ?뱀씤 ??諛섏쁺?⑸땲?? ?숈깮 ?묒꽦 ?댁슜? ?먮룞 ??뼱?곌린?섏? ?딆뒿?덈떎.'
                        : '梨꾪똿 以??뱀뀡 ?쒖븞???ㅼ떆媛꾩쑝濡??곌껐?⑸땲?? ?뱀씤 ?꾩뿉???숈깮 ?묒꽦 臾몃떒??蹂댄샇?⑸땲??'
                    }
                  />
                </div>
              ) : (
                <p className={cn('text-xs font-semibold text-slate-500', advancedMode && 'lg:w-1/2')}>
                  珥덉븞 ?듭뀡???④꺼???덉뒿?덈떎. 紐⑤뱶/?④퀎 議곗젙???꾩슂???뚮쭔 ?쇱퀜???ъ슜?섏꽭??
                </p>
              )}

              <div
                className={cn(
                  "mt-3 w-full min-h-0 flex-1 space-y-3 overflow-y-auto pr-1 custom-scrollbar",
                  advancedMode && "lg:w-1/2",
                )}
              >
                {BLOCK_DEFINITIONS.map((definition) => {
                  const block =
                    structuredDraft.blocks.find((item) => item.block_id === definition.id) || {
                      block_id: definition.id,
                      heading: definition.heading,
                      content_markdown: '',
                      attribution: 'student-authored' as WorkshopDraftAttribution,
                    };
                  const attributionStatus =
                    block.attribution === 'student-authored'
                      ? 'success'
                      : block.attribution === 'ai-inserted-after-approval'
                        ? 'active'
                        : 'warning';
                  return (
                    <SurfaceCard key={definition.id} className="border-slate-200 bg-white p-3 shadow-sm">
                      <div className="mb-2 flex items-center justify-between gap-2">
                        <input
                          value={block.heading}
                          onChange={(event) => updateDraftHeading(definition.id, event.target.value)}
                          className="w-full rounded-lg border border-slate-200 bg-slate-50 px-2 py-1.5 text-xs font-bold text-slate-800 outline-none focus:border-[#004aad] focus:bg-white"
                        />
                        <StatusBadge status={attributionStatus}>
                          {formatDraftAttributionLabel(block.attribution)}
                        </StatusBadge>
                      </div>
                      {definition.id === 'title' ? (
                        <input
                          value={block.content_markdown}
                          onChange={(event) => updateDraftBlock(definition.id, event.target.value)}
                          placeholder="?쒕ぉ"
                          className="h-10 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm font-semibold text-slate-800 outline-none focus:border-[#004aad] focus:bg-white"
                        />
                      ) : (
                        <textarea
                          value={block.content_markdown}
                          onChange={(event) => updateDraftBlock(definition.id, event.target.value)}
                          placeholder={`${block.heading} 내용을 작성해 주세요.`}
                          className="min-h-[110px] w-full resize-y rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm font-medium leading-6 text-slate-800 outline-none focus:border-[#004aad] focus:bg-white"
                        />
                      )}
                    </SurfaceCard>
                  );
                })}
              </div>
              
              {advancedMode ? (
                <div className="mt-4 space-y-3 lg:mt-0 lg:w-1/2">
                  <button
                    type="button"
                    onClick={() => setShowAdvancedTools(prev => !prev)}
                    className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3 text-xs font-bold text-slate-600 transition-colors hover:bg-slate-50"
                  >
                    {showAdvancedTools ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                    怨좉툒 ?꾧뎄
                  </button>

                  {showAdvancedTools ? (
                    <div className="flex flex-col gap-4 overflow-y-auto pr-1 custom-scrollbar">
                      <EvidenceDrawer evidenceMap={renderArtifact?.evidence_map ?? null} />
                      <SurfaceCard className="border-[#004aad]/5 bg-[#004aad]/5 p-4 shadow-sm">
                        <AdvancedPreview
                          workshopId={workshopState?.session.id || ''}
                          artifactId={workshopState?.latest_artifact?.id || ''}
                          isAdvancedMode={advancedMode}
                          visualSpecs={renderArtifact?.visual_specs ?? []}
                          mathExpressions={renderArtifact?.math_expressions ?? []}
                          onUpdateVisualStatus={handleUpdateVisualStatus}
                          onReplaceVisual={handleReplaceVisual}
                        />
                      </SurfaceCard>
                    </div>
                  ) : (
                    <p className="text-sm font-bold text-slate-400">
                      ?몃? ?쒓컖???붿냼媛 ?좏깮?섏뿀?쇰굹, ?꾩옱 ?섍꼍?먯꽌??誘몃━蹂닿린瑜??쒓났?????놁뒿?덈떎.
                    </p>
                  )}
                </div>
              ) : null}
            </div>
          </SectionCard>
        </div>
      </motion.div>
    </div>
  );
}






