import React, { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import {
  Bot,
  ChevronDown,
  ChevronUp,
  Download,
  FileText,
  Loader2,
  RotateCcw,
  Send,
  Sparkles,
  ToggleLeft,
  ToggleRight,
  User,
  WandSparkles,
  ExternalLink,
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import 'katex/dist/katex.min.css';
import { useLocation, useParams, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import confetti from 'canvas-confetti';
import { auth } from '../lib/firebase';
import { api, resolveApiBaseUrl } from '../lib/api';
import { cn } from '../lib/cn';
import { saveArchiveItem } from '../lib/archiveStore';
import { readQuestStart } from '../lib/questStart';
import { AdvancedPreview } from '../components/AdvancedPreview';
import { ReferenceSearchPanel } from '../components/ReferenceSearchPanel';
import { EvidenceDrawer } from '../components/EvidenceDrawer';
import { SuggestionReviewModal } from '../components/SuggestionReviewModal';
import {
  EmptyState,
  PageHeader,
  PrimaryButton,
  SecondaryButton,
  SectionCard,
  StatusBadge,
  SurfaceCard,
  WorkflowNotice,
} from '../components/primitives';

const MemoizedMarkdown = memo(function MemoizedMarkdown({
  content,
  role = 'foli',
}: {
  content: string;
  role?: MessageRole | 'document';
}) {
  const isUserMessage = role === 'user';

  return (
    <ReactMarkdown
      remarkPlugins={[remarkMath]}
      rehypePlugins={[rehypeKatex]}
      components={{
        h3: ({ children, ...props }) => {
          const text = React.Children.toArray(children).join('');
          const isAISuggestion = !isUserMessage && (text.includes('[AI 제안 초안]') || text.includes('[AI Draft Suggestion]'));

          if (isAISuggestion) {
            return (
              <h3
                {...props}
                className="mb-4 mt-8 flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-3 py-2 text-sm font-bold text-blue-800"
              >
                <span className="inline-flex h-5 w-5 items-center justify-center rounded-lg bg-blue-600 text-[10px] font-black text-white">AI</span>
                {children}
              </h3>
            );
          }

          return <h3 {...props} className={isUserMessage ? 'mb-3 mt-5 text-base font-bold text-slate-100' : 'mb-3 mt-6 text-lg font-bold text-slate-900'} />;
        },
        p: ({ children, ...props }) => {
          const text = React.Children.toArray(children).join('');
          const isAINote =
            !isUserMessage && (text.includes('Foli가 생성한 제안 문장입니다') || text.includes('This text was generated by Foli'));

          if (isAINote) {
            return (
              <p
                {...props}
                className="mb-5 rounded-lg border-l-4 border-blue-300 bg-blue-50 px-3 py-2 text-sm font-medium italic text-slate-600"
              />
            );
          }

          return <p {...props} className={isUserMessage ? 'whitespace-pre-wrap text-sm leading-7 text-slate-100' : 'text-sm leading-7 text-slate-700'} />;
        },
      }}
    >
      {content}
    </ReactMarkdown>
  );
});

export type QualityLevel = 'low' | 'mid' | 'high';
type MessageRole = 'user' | 'foli';

interface Message {
  id: string;
  role: MessageRole;
  content: string;
  suggestedContent?: string;
}

interface DraftArtifact {
  id: string;
  report_markdown: string;
  visual_specs: any[];
  math_expressions: any[];
  evidence_map?: Record<string, any> | null;
}

interface WorkshopSessionResponse {
  id: string;
  project_id: string;
  quest_id: string | null;
  status: string;
  quality_level: QualityLevel;
  turns?: Array<{
    id: string;
    turn_type: 'user' | 'assistant';
    query?: string;
    response?: string;
  }>;
}

interface WorkshopStateResponse {
  session: WorkshopSessionResponse;
  starter_choices: unknown[];
  followup_choices: unknown[];
  message: string | null;
  latest_artifact: DraftArtifact | null;
}

const QUALITY_META_MAP: Record<QualityLevel, { label: string; status: 'success' | 'active' | 'warning' }> = {
  low: { label: '빠른 응답', status: 'success' },
  mid: { label: '균형 모드', status: 'active' },
  high: { label: '심화 모드', status: 'warning' },
};

const AI_SUGGESTION_HEADER = '### [AI 제안 초안]';
const LEGACY_AI_SUGGESTION_HEADER = '### [AI Draft Suggestion]';
const AI_SUGGESTION_NOTE =
  '> 반영 전 검토해 주세요. 이 문장은 Foli가 생성한 제안 문장입니다. 수정 후 승인하기 전까지 학생 작성본으로 간주되지 않습니다.';
const LEGACY_AI_SUGGESTION_NOTE =
  '> Review before keeping. This text was generated by Foli and is not student-authored until you edit and accept it.';

function isKorean(text: string) {
  return /[ㄱ-ㅎㅏ-ㅣ가-힣]/.test(text);
}

function buildFoliFallback(message: string) {
  const clean = message.toLowerCase().trim();
  const greetings = ['안녕', '반가워', '하이', '안녕하세요', 'hello', 'hi', 'hey'];

  if (greetings.some(token => clean.includes(token))) {
    return [
      '안녕하세요. Uni Folia 워크숍입니다.',
      '',
      '현재 일부 고급 기능이 제한되어 있어도, 초안 구조화와 문장 개선은 계속 도와드릴 수 있습니다.',
    ].join('\n');
  }

  return [
    '현재 연결 문제로 자동 근거 검증이 제한되어 있습니다.',
    '',
    '대신 아래 작업은 바로 도와드릴 수 있어요:',
    '1. 연구 질문 구체화',
    '2. 필요한 근거 목록 정리',
    '3. 보고서 구조 설계',
  ].join('\n');
}

async function streamFoliReply(projectId: string | undefined, message: string, onDelta?: (delta: string) => void) {
  const baseUrl = resolveApiBaseUrl();
  const token = auth?.currentUser ? await auth.currentUser.getIdToken() : null;
  let response: Response;

  try {
    response = await fetch(`${baseUrl}/api/v1/drafts/chat/stream`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) },
      body: JSON.stringify({ project_id: projectId, message, reference_materials: [] }),
    });
  } catch {
    if (!projectId) return buildFoliFallback(message);
    throw new Error('NETWORK_FAIL');
  }

  if (!response.ok || !response.body) {
    if (!projectId) return buildFoliFallback(message);
    if (response.status === 429) throw new Error('RATE_LIMIT');
    if (response.status === 401 || response.status === 403) throw new Error('AUTH_REQUIRED');
    throw new Error('STREAM_FAIL');
  }

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let full = '';
  let buffer = '';

  while (true) {
    const { done, value } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const chunks = buffer.split('\n\n');
    buffer = chunks.pop() || '';

    for (const event of chunks) {
      const line = event.split('\n').find(item => item.startsWith('data:'));
      if (!line) continue;

      let payload: Record<string, unknown>;
      try {
        payload = JSON.parse(line.replace(/^data:\s*/, ''));
      } catch {
        continue;
      }

      if (payload.done) break;
      if (typeof payload.error === 'string' && payload.error.trim()) throw new Error(payload.error.trim());

      if (typeof payload.token === 'string' && payload.token) {
        full += payload.token;
        onDelta?.(payload.token);
      }
    }
  }

  return full.trim();
}

const ChatBubble = memo(function ChatBubble({
  message,
  onSuggestClick,
}: {
  message: Message;
  onSuggestClick: (content: string) => void;
}) {
  const isUser = message.role === 'user';

  return (
    <div className={`flex gap-3 ${isUser ? 'flex-row-reverse' : ''}`}>
      <div
        className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-xl text-xs font-black ${
          isUser ? 'bg-slate-100 text-slate-500' : 'bg-blue-600 text-white'
        }`}
      >
        {isUser ? <User size={14} /> : 'F'}
      </div>

      <div
        className={`max-w-[88%] rounded-2xl border px-4 py-3 shadow-sm ${
          isUser ? 'border-slate-200 bg-slate-900 text-white' : 'border-slate-200 bg-white text-slate-700'
        }`}
      >
        <MemoizedMarkdown content={String(message.content || '')} role={message.role} />
        {message.suggestedContent ? (
          <SecondaryButton size="sm" className="mt-3" onClick={() => onSuggestClick(message.suggestedContent || '')}>
            제안 초안 검토
          </SecondaryButton>
        ) : null}
      </div>
    </div>
  );
});

export function Workshop() {
  const { projectId } = useParams<{ projectId: string }>();
  const location = useLocation();
  const navigate = useNavigate();

  const [workshopState, setWorkshopState] = useState<WorkshopStateResponse | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isSessionLoading, setIsSessionLoading] = useState(true);
  const [documentContent, setDocumentContent] = useState('');
  const [qualityLevel, setQualityLevel] = useState<QualityLevel>('mid');
  const [advancedMode, setAdvancedMode] = useState(false);
  const [renderArtifact, setRenderArtifact] = useState<DraftArtifact | null>(null);
  const [diagnosisReport, setDiagnosisReport] = useState<Record<string, unknown> | null>(null);
  const [showDiagnosis, setShowDiagnosis] = useState(false);
  const [isRendering, setIsRendering] = useState(false);
  const [docHistory, setDocHistory] = useState<string[]>([]);
  const [historyIndex, setHistoryIndex] = useState(-1);
  const [pendingSuggestion, setPendingSuggestion] = useState<string | null>(null);
  const [mobileView, setMobileView] = useState<'chat' | 'draft'>('chat');
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const questStart = useMemo(() => readQuestStart(), []);
  const initialMajor = useMemo(() => ((location.state as { major?: string } | null)?.major || '미지정'), [location.state]);
  const isProjectBacked = Boolean(projectId && projectId !== 'demo');
  const fileName = useMemo(() => `${(questStart?.title || '초안').replace(/\s+/g, '_')}.hwpx`, [questStart]);

  useEffect(() => {
    const savedLevel = localStorage.getItem('folia_quality_level');
    if (savedLevel === 'low' || savedLevel === 'mid' || savedLevel === 'high') setQualityLevel(savedLevel as QualityLevel);

    setDocumentContent(
      questStart?.document_seed_markdown || `# [연구 초안] ${questStart?.title || '새 주제'}\n\n**전공:** ${initialMajor}\n\n## 1. 연구 동기`,
    );

    if (isProjectBacked) void initWorkshop();
    else {
      setIsSessionLoading(false);
      setMessages([{ id: 'demo-init', role: 'foli', content: '데모 모드입니다. Foli에게 질문하면 초안 작성을 도와드립니다.' }]);
    }
  }, [initialMajor, isProjectBacked, questStart?.document_seed_markdown, questStart?.title]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  useEffect(() => {
    if (!workshopState?.session.id || !documentContent) return;

    const timeout = setTimeout(() => {
      api
        .put(`/api/v1/workshops/${workshopState.session.id}/drafts/latest`, { document_content: documentContent })
        .catch(error => console.error('Autosave failed:', error));
    }, 3000);

    return () => clearTimeout(timeout);
  }, [documentContent, workshopState?.session.id]);

  useEffect(() => {
    if (!documentContent.includes('### [AI')) return;

    const normalizedMarker = documentContent
      .replace(/### \[AI[^\]]*\]/g, AI_SUGGESTION_HEADER)
      .replace(LEGACY_AI_SUGGESTION_HEADER, AI_SUGGESTION_HEADER)
      .replace(LEGACY_AI_SUGGESTION_NOTE, AI_SUGGESTION_NOTE);
    const normalizedContent = normalizedMarker.includes(AI_SUGGESTION_NOTE)
      ? normalizedMarker
      : normalizedMarker.replace(AI_SUGGESTION_HEADER, `${AI_SUGGESTION_HEADER}\n${AI_SUGGESTION_NOTE}`);

    if (normalizedContent !== documentContent) setDocumentContent(normalizedContent);
  }, [documentContent]);

  const initWorkshop = useCallback(async () => {
    setIsSessionLoading(true);
    try {
      const sessions = await api.get<WorkshopSessionResponse[]>(`/api/v1/workshops?project_id=${projectId}`);
      const active = sessions.find(session => session.status !== 'completed');
      const state = active
        ? await api.get<WorkshopStateResponse>(`/api/v1/workshops/${active.id}`)
        : await api.post<WorkshopStateResponse>('/api/v1/workshops', { project_id: projectId, quality_level: qualityLevel });

      setWorkshopState(state);
      setQualityLevel(state.session.quality_level);

      if (state.latest_artifact) {
        setRenderArtifact(state.latest_artifact);
        setDocumentContent(state.latest_artifact.report_markdown);
      }

      const turns = state.session.turns || [];
      const loadedMessages: Message[] = turns.map(turn => ({
        id: turn.id,
        role: turn.turn_type === 'user' ? 'user' : 'foli',
        content: turn.turn_type === 'user' ? turn.query || '' : turn.response || '',
      }));

      setMessages(
        loadedMessages.length
          ? loadedMessages
          : [{ id: 'init', role: 'foli', content: state.message || '반갑습니다. 어떤 부분을 먼저 보완할까요?' }],
      );
    } catch (error) {
      console.error('Workshop init failed:', error);
      toast.error('워크숍 상태를 불러오지 못했습니다. 로컬 초안 모드로 전환합니다.');
      setMessages([{ id: 'fallback-init', role: 'foli', content: '이전 세션을 불러오지 못했습니다. 로컬 초안 작성은 계속 가능합니다.' }]);
    } finally {
      setIsSessionLoading(false);
    }

    try {
      const diagnosis = await api.get<{ result_payload?: Record<string, unknown> }>(`/api/v1/diagnosis/project/${projectId}/latest`);
      if (diagnosis?.result_payload) {
        setDiagnosisReport(diagnosis.result_payload);
        setShowDiagnosis(true);
      }
    } catch {
      // optional
    }
  }, [projectId, qualityLevel]);

  const handleSend = async (overriddenText?: string) => {
    const text = (overriddenText ?? input).trim();
    if (!text || isTyping) return;
    if (!overriddenText) setInput('');

    setMessages(prev => [...prev, { id: crypto.randomUUID(), role: 'user', content: text }]);
    setIsTyping(true);

    const foliId = crypto.randomUUID();
    setMessages(prev => [...prev, { id: foliId, role: 'foli', content: '' }]);

    let accumulated = '';
    let pendingDelta = '';
    let flushTimer: number | null = null;

    const flushBufferedDelta = () => {
      if (!pendingDelta) {
        flushTimer = null;
        return;
      }
      accumulated += pendingDelta;
      pendingDelta = '';
      flushTimer = null;
      setMessages(prev => prev.map(message => (message.id === foliId ? { ...message, content: accumulated } : message)));
    };

    try {
      const raw = await streamFoliReply(isProjectBacked ? projectId : undefined, text, delta => {
        pendingDelta += delta;
        if (flushTimer === null) {
          flushTimer = window.setTimeout(flushBufferedDelta, 40);
        }
      });

      if (flushTimer !== null) {
        window.clearTimeout(flushTimer);
        flushTimer = null;
      }
      flushBufferedDelta();

      const tagMatch = raw.match(/\[CONTENT\]([\s\S]*?)\[\/CONTENT\]/);
      if (tagMatch) {
        setMessages(prev =>
          prev.map(message =>
            message.id === foliId
              ? {
                  ...message,
                  content: raw.replace(/\[CONTENT\][\s\S]*?\[\/CONTENT\]/, '').trim(),
                  suggestedContent: tagMatch[1].trim(),
                }
              : message,
          ),
        );
      } else {
        setMessages(prev =>
          prev.map(message =>
            message.id === foliId ? { ...message, content: raw || accumulated || '응답을 생성하지 못했습니다.' } : message,
          ),
        );
      }

      if (isProjectBacked && workshopState) {
        const updated = await api.post<WorkshopStateResponse>(`/api/v1/workshops/${workshopState.session.id}/messages`, { message: text });
        setWorkshopState(updated);
        if (updated.message) setMessages(prev => [...prev, { id: crypto.randomUUID(), role: 'foli', content: updated.message || '' }]);
      }
    } catch (error) {
      console.error('AI reply stream failed:', error);
      if (error instanceof Error && error.message === 'RATE_LIMIT') toast.error('요청이 많습니다. 잠시 후 다시 시도해 주세요.');
      else if (error instanceof Error && error.message === 'AUTH_REQUIRED') toast.error('세션이 만료되었습니다. 다시 로그인해 주세요.');
      else if (error instanceof Error && error.message === 'NETWORK_FAIL') toast.error('초안 서비스에 연결하지 못했습니다.');
      else if (error instanceof Error && error.message === 'STREAM_FAIL') toast.error('응답 스트림 처리에 실패했습니다.');
      else if (error instanceof Error) toast.error(error.message);
      else toast.error('응답 생성에 실패했습니다.');
    } finally {
      setIsTyping(false);
    }
  };

  const applySuggestedContent = (content: string) => {
    if (documentContent.includes(content)) {
      setPendingSuggestion(null);
      return;
    }

    const marker = `${AI_SUGGESTION_HEADER}\n${AI_SUGGESTION_NOTE}`;
    const updated = `${documentContent}\n\n${marker}\n\n${content}`;

    setDocHistory(prev => {
      const trimmed = prev.slice(0, historyIndex + 1);
      trimmed.push(documentContent);
      return trimmed.slice(-20);
    });
    setHistoryIndex(prev => Math.min(prev + 1, 19));

    setDocumentContent(updated);
    setPendingSuggestion(null);
    toast.success('제안 초안을 문서에 반영했습니다.');
  };

  const undoLastChange = () => {
    if (historyIndex >= 0 && docHistory[historyIndex] !== undefined) {
      setDocumentContent(docHistory[historyIndex]);
      setHistoryIndex(prev => prev - 1);
      toast.success('직전 편집을 되돌렸습니다.');
    }
  };

  const handleGenerateDraft = async () => {
    if (!workshopState || isRendering) return;
    setIsRendering(true);
    try {
      await api.post(`/api/v1/workshops/${workshopState.session.id}/render`);
      toast.success('초안 렌더링을 요청했습니다.');
    } catch (error) {
      console.error('Failed to render draft:', error);
      toast.error('렌더링 요청에 실패했습니다.');
    } finally {
      setIsRendering(false);
    }
  };

  const handleSaveDraft = () => {
    saveArchiveItem({
      id: crypto.randomUUID(),
      projectId: projectId ?? null,
      title: fileName.replace('.hwpx', ''),
      subject: initialMajor,
      createdAt: new Date().toISOString(),
      contentMarkdown: documentContent,
    });
    toast.success('초안을 아카이브에 저장했습니다.');
    confetti({ particleCount: 80, spread: 62, origin: { y: 0.65 } });
  };

  const handleUpdateVisualStatus = async (visualId: string, status: string) => {
    if (!workshopState?.session.id || !workshopState?.latest_artifact?.id) return;
    try {
      let updated: WorkshopStateResponse;
      if (status === 'replaced') {
        updated = await api.post<WorkshopStateResponse>(
          `/api/v1/workshops/${workshopState.session.id}/artifacts/${workshopState.latest_artifact.id}/visuals/${visualId}/replace`,
        );
      } else {
        updated = await api.patch<WorkshopStateResponse>(
          `/api/v1/workshops/${workshopState.session.id}/artifacts/${workshopState.latest_artifact.id}/visuals/${visualId}`,
          { approval_status: status },
        );
      }
      setWorkshopState(updated);
      toast.success(status === 'approved' ? '시각 자료를 승인했습니다.' : status === 'rejected' ? '시각 자료를 제외했습니다.' : '시각 자료 상태를 갱신했습니다.');
    } catch (error) {
      console.error('Failed to update visual status:', error);
      toast.error('시각 자료 상태 갱신에 실패했습니다.');
    }
  };

  const qualityMeta = QUALITY_META_MAP[qualityLevel] || QUALITY_META_MAP.mid;
  const diagnosisHeadline = typeof diagnosisReport?.headline === 'string' ? diagnosisReport.headline : null;
  const diagnosisRisk = typeof diagnosisReport?.risk_level === 'string' ? diagnosisReport.risk_level : null;
  const diagnosisRecommendedFocus = typeof diagnosisReport?.recommended_focus === 'string' ? diagnosisReport.recommended_focus : null;
  const diagnosisGapCount = Array.isArray(diagnosisReport?.gaps) ? diagnosisReport.gaps.length : 0;

  return (
    <div className={cn("mx-auto max-w-7xl space-y-5 px-3 py-4 transition-all duration-700 sm:space-y-6 sm:px-4 sm:py-6", advancedMode && "rounded-[32px] bg-blue-50/30 shadow-[inset_0_0_100px_rgba(37,99,235,0.03)] sm:rounded-[48px]")}>
      <motion.div
        animate={advancedMode ? { y: [0, -2, 0] } : {}}
        transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
      >
        <PageHeader
        eyebrow="워크숍"
        title="초안 작성 및 개선 워크스페이스"
        description="Foli와 대화하며 근거 중심 초안을 작성하고, 사용자 검토 후 문서에 반영하세요."
        actions={
          <>
            <SecondaryButton
              data-testid="workshop-advanced-toggle"
              onClick={() => setAdvancedMode(prev => !prev)}
              aria-label={advancedMode ? '고급 모드 끄기' : '고급 모드 켜기'}
            >
              {advancedMode ? <ToggleRight size={16} /> : <ToggleLeft size={16} />}
              {advancedMode ? '고급 모드 켜짐' : '고급 모드 꺼짐'}
            </SecondaryButton>
            <PrimaryButton onClick={handleGenerateDraft} disabled={!workshopState || isRendering}>
              {isRendering ? <Loader2 size={16} className="animate-spin" /> : <WandSparkles size={16} />}
              {isRendering ? '렌더링 중...' : '결과물 생성'}
            </PrimaryButton>
          </>
        }
        evidence={
          <div className="flex flex-wrap items-center gap-2">
            <StatusBadge status={isProjectBacked ? 'success' : 'warning'}>{isProjectBacked ? '프로젝트 연동' : '데모 모드'}</StatusBadge>
            <StatusBadge status={qualityMeta.status}>품질 {qualityLevel.toUpperCase()}</StatusBadge>
            <StatusBadge status={advancedMode ? 'active' : 'neutral'}>{advancedMode ? '고급 기능 사용 중' : '기본 기능 사용 중'}</StatusBadge>
            {diagnosisReport ? <StatusBadge status="active">진단 연동됨</StatusBadge> : null}
          </div>
        }
      />

      <SuggestionReviewModal
        isOpen={Boolean(pendingSuggestion)}
        content={pendingSuggestion}
        onApply={() => pendingSuggestion && applySuggestedContent(pendingSuggestion)}
        onCancel={() => setPendingSuggestion(null)}
      />

      <div className="md:hidden">
        <div className="inline-flex w-full items-center gap-1 rounded-2xl border border-slate-200 bg-white p-1 shadow-sm">
          <button
            type="button"
            onClick={() => setMobileView('chat')}
            className={cn(
              'h-10 flex-1 rounded-xl px-3 text-sm font-bold transition-colors',
              mobileView === 'chat' ? 'bg-blue-600 text-white' : 'text-slate-600 hover:bg-slate-100',
            )}
          >
            대화
          </button>
          <button
            type="button"
            onClick={() => setMobileView('draft')}
            className={cn(
              'h-10 flex-1 rounded-xl px-3 text-sm font-bold transition-colors',
              mobileView === 'draft' ? 'bg-blue-600 text-white' : 'text-slate-600 hover:bg-slate-100',
            )}
          >
            초안 문서
          </button>
        </div>
      </div>

      <div className="grid gap-4 md:gap-6 lg:grid-cols-[minmax(0,380px)_minmax(0,1fr)]">
        <SectionCard
          title="Foli 대화"
          description="핵심 질문으로 논리 구조, 근거 연결, 문장 완성도를 순서대로 개선해 보세요."
          eyebrow="대화"
          className={cn('min-h-[34rem] md:min-h-[38rem]', mobileView !== 'chat' && 'hidden md:flex')}
          bodyClassName="flex h-full min-h-0 flex-col gap-4 space-y-0"
          actions={<StatusBadge status={qualityMeta.status}>{qualityMeta.label}</StatusBadge>}
        >
          {diagnosisReport ? (
            <SurfaceCard tone="muted" padding="none" className="overflow-hidden">
              <button
                type="button"
                onClick={() => setShowDiagnosis(prev => !prev)}
                className="flex w-full items-center justify-between px-4 py-3 text-left text-sm font-bold text-slate-700 hover:bg-slate-100"
              >
                <span className="inline-flex items-center gap-2">
                  <Sparkles size={15} className="text-blue-600" />
                  진단 요약 보기
                </span>
                {showDiagnosis ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
              </button>
              <AnimatePresence initial={false}>
                {showDiagnosis ? (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="overflow-hidden border-t border-slate-200 px-4 pb-4"
                  >
                    <SurfaceCard padding="sm" className="mt-3 space-y-2">
                      <p className="text-sm font-bold text-slate-900">{diagnosisHeadline || '최근 진단 요약'}</p>
                      <div className="flex flex-wrap items-center gap-2">
                        {diagnosisRisk ? <StatusBadge status={diagnosisRisk === 'safe' ? 'success' : 'warning'}>{diagnosisRisk}</StatusBadge> : null}
                        <StatusBadge status="neutral">보완 항목 {diagnosisGapCount}개</StatusBadge>
                      </div>
                      {diagnosisRecommendedFocus ? <p className="text-sm font-medium leading-6 text-slate-600">{diagnosisRecommendedFocus}</p> : null}
                    </SurfaceCard>
                  </motion.div>
                ) : null}
              </AnimatePresence>
            </SurfaceCard>
          ) : null}

          <div className="min-h-0 flex-1 overflow-y-auto rounded-2xl border border-slate-200 bg-slate-50 p-3" tabIndex={0} aria-label="워크숍 대화">
            {isSessionLoading ? (
              <div className="flex h-full items-center justify-center">
                <div className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-600">
                  <Loader2 size={16} className="animate-spin text-blue-600" />
                  워크숍 세션을 불러오는 중...
                </div>
              </div>
            ) : messages.length ? (
              <div className="space-y-4">
                {messages.map(message => (
                  <ChatBubble key={message.id} message={message} onSuggestClick={content => setPendingSuggestion(content)} />
                ))}
                {isTyping ? (
                  <div className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-2 text-xs font-semibold text-slate-500">
                    <Loader2 size={12} className="animate-spin text-blue-600" />
                    Foli가 답변을 작성 중입니다...
                  </div>
                ) : null}
                <div ref={messagesEndRef} />
              </div>
            ) : (
              <EmptyState title="아직 대화가 없습니다" description="먼저 질문을 입력하면 초안 개선 제안을 받을 수 있습니다." icon={<Bot size={20} />} />
            )}
          </div>

          {advancedMode ? (
            isProjectBacked ? (
              <ReferenceSearchPanel
                isAdvancedMode={advancedMode}
                onPinReference={async (text, source) => {
                  if (!workshopState) return;
                  const updated = await api.post<WorkshopStateResponse>(`/api/v1/workshops/${workshopState.session.id}/references/pin`, {
                    text_content: text,
                    source_type: source,
                  });
                  setWorkshopState(updated);
                  toast.success('참고 근거를 워크숍 컨텍스트에 고정했습니다.');
                }}
              />
            ) : (
              <WorkflowNotice tone="warning" title="고급 근거 검색은 프로젝트 연동 모드에서 사용할 수 있습니다." />
            )
          ) : null}

          <div className="sticky bottom-0 z-10 -mx-1 flex items-center gap-2 border-t border-slate-200 bg-white/95 px-1 pt-3 pb-[calc(0.25rem+env(safe-area-inset-bottom))] backdrop-blur md:static md:mx-0 md:border-0 md:bg-transparent md:px-0 md:pt-0 md:pb-0">
            <SecondaryButton onClick={() => toast.success('내보내기 기능은 다음 단계에서 연결됩니다.')} aria-label="초안 내보내기" size="icon">
              <Download size={16} />
            </SecondaryButton>
            <input
              value={input}
              onChange={event => setInput(event.target.value)}
              onKeyDown={event => {
                if (event.key === 'Enter') {
                  event.preventDefault();
                  void handleSend();
                }
              }}
              placeholder="논지 구성, 근거 연결, 문장 다듬기 등 요청을 입력해 주세요."
              className="h-11 min-w-0 flex-1 rounded-2xl border border-slate-300 bg-white px-4 text-sm font-medium text-slate-700 outline-none transition focus-visible:ring-2 focus-visible:ring-blue-300"
            />
            <PrimaryButton onClick={() => void handleSend()} disabled={!input.trim() || isTyping} aria-label="메시지 전송" size="icon">
              <Send size={16} />
            </PrimaryButton>
          </div>
        </SectionCard>

        <SectionCard
          title="초안 문서"
          description="학생 작성 문장을 중심으로 유지하고, AI 제안은 검토 후 반영하세요."
          eyebrow="문서"
          className={cn('min-h-[34rem] md:min-h-[38rem]', mobileView !== 'draft' && 'hidden md:flex')}
          bodyClassName="flex h-full min-h-0 flex-col gap-4 space-y-0"
          actions={
            <div className="flex flex-wrap items-center gap-2">
              <SecondaryButton
                data-testid="workshop-open-editor"
                onClick={() => navigate(`/app/editor/${projectId ?? 'demo'}`, { state: { seedMarkdown: documentContent } })}
                size="sm"
                className="border-blue-200 bg-blue-50 text-blue-700 hover:bg-blue-100"
              >
                <ExternalLink size={14} />
                전문 에디터
              </SecondaryButton>
              <SecondaryButton data-testid="workshop-undo" onClick={undoLastChange} disabled={historyIndex < 0} size="sm">
                <RotateCcw size={14} />
                되돌리기
              </SecondaryButton>
              <PrimaryButton onClick={handleGenerateDraft} disabled={!workshopState || isRendering} size="sm">
                {isRendering ? <Loader2 size={14} className="animate-spin" /> : <WandSparkles size={14} />}
                {isRendering ? '생성 중...' : '렌더링'}
              </PrimaryButton>
              <SecondaryButton data-testid="workshop-save-draft" onClick={handleSaveDraft} size="sm">
                저장
              </SecondaryButton>
            </div>
          }
        >
          <WorkflowNotice
            tone="info"
            title="신뢰 원칙"
            description="AI 문구는 사용자의 승인 후에만 삽입되며, 삽입된 위치는 문서에서 명시적으로 표시됩니다."
          />

          <div
            className="min-h-0 flex-1 overflow-y-auto rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:p-6"
            tabIndex={0}
            aria-label="초안 미리보기 문서"
            data-testid="workshop-draft-preview"
          >
            <div className="mx-auto flex min-h-[520px] w-full max-w-full flex-col rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:min-h-[720px] sm:max-w-[210mm] sm:p-10">
              <div className="mb-4 flex items-center justify-between border-b border-slate-100 pb-3">
                <p className="truncate text-xs font-bold uppercase tracking-[0.14em] text-slate-400">{fileName}</p>
                <StatusBadge status="neutral">실시간 미리보기</StatusBadge>
              </div>

              <div className="prose prose-sm max-w-none prose-headings:font-bold prose-p:leading-7 prose-p:text-slate-700">
                {documentContent ? (
                  <MemoizedMarkdown content={documentContent} />
                ) : (
                  <EmptyState title="초안이 비어 있습니다" description="왼쪽 대화에서 문단 생성을 요청해 초안을 시작해 보세요." icon={<FileText size={20} />} className="mt-12" />
                )}
              </div>
            </div>

            <EvidenceDrawer evidenceMap={renderArtifact?.evidence_map ?? null} />

            <SurfaceCard className="mt-6 p-4">
              <AdvancedPreview
                workshopId={workshopState?.session.id || ''}
                artifactId={workshopState?.latest_artifact?.id || ''}
                isAdvancedMode={advancedMode}
                visualSpecs={renderArtifact?.visual_specs ?? []}
                mathExpressions={renderArtifact?.math_expressions ?? []}
                onUpdateVisualStatus={handleUpdateVisualStatus}
              />
            </SurfaceCard>
          </div>
        </SectionCard>
      </div>
      </motion.div>
    </div>
  );
}
